### ISSUE TITLE
A-to-B 

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/nelsonic.github.io#10]
**_In London we cycle**_. there's simply _no question_ that its the **_best way**_ to get around!
But to visit our Family in Portugal, we _usually_ fly.
(I say usually, because we have once done it by rail; it took a bit longer...!)

**Comment by nelsonic** [comment]
But how feasible is it to **_drive**_...?
http://www.viamichelin.co.uk/web/Routes/Route-London-_-Greater_London-United_Kingdom-to-Lisbon-_-Lisboa-Portugal

![volvo-xc90-full-spec](https://cloud.githubusercontent.com/assets/194400/7716157/dc55e478-fe86-11e4-9084-c53d6d7a929f.png)

http://www.countrycarshop.co.uk/used-cars/volvo-xc90-2-4-td-d5-se-geartronic-5dr-isham-201505023130799

**Comment by nelsonic** [comment]
Plates

![personalised-numberplate-dwyl](https://cloud.githubusercontent.com/assets/194400/7716160/e03e2f96-fe86-11e4-9467-6965f44c31d4.png)

http://dvlaregistrations.direct.gov.uk/howtobuy.html?plate=AD65%20WYL&price=399

**_or**_

![personalised-numberplate-d8wyl](https://cloud.githubusercontent.com/assets/194400/7716434/070680c6-fe8a-11e4-87f6-6fa83c54527f.png)

http://dvlaregistrations.direct.gov.uk/buy.html?plate=D8%20WYL&price=499

**Comment by nelsonic** [comment]
Insurance quote for this _exact_ vehicle:

![insurance-compare](https://cloud.githubusercontent.com/assets/194400/7717974/d2eef972-fea1-11e4-9099-e15b7a67cfed.png)

![insurance-quote](https://cloud.githubusercontent.com/assets/194400/7717975/d8dabd76-fea1-11e4-84af-9e937a98d764.png)

**Comment by nelsonic** [comment]
## Cost - £10,566
- Car: £5,995
- Road Tax: £295
- Insurance: £1,856
- Fuel: £600
- Channel Tunnel: £220
- Food: £400
- Accommodation: £600
- Entertainment: £600

Of which we could recover £5,000 by selling the car when we get back.
While this does not sound like much in terms of software development contracting in London.
It means we would be spending £5k more than we **_need**_ to in order to get us from A-to-B!

If we pay people £10 per hour to work on building the product, that's **_FIVE HUNDRED HOURS**_!!
Or to put it another way, if a person worked 7h a day for us, 5 days a week (i.e. 35h per week)
the £5k would be enough to pay a person for **FOURTEEN WEEKS**! :open_mouth:

**Comment by nelsonic** [comment]
@iteles **_thank you**_ for talking sense into me. 
buying a car just to drive to PT this summer is a **_massive**_ squandering of our Capital!
Our **_RULE**_ should be:

# if it does not move us closer to solving people's problems (_and paying to use our product_) its a waste of time/money!

Thoughts?

**Comment by nelsonic** [comment]
@iteles lets book the flights home for July. :+1:

**Comment by nelsonic** [comment]
how much are taxis from Porto airport to Geres?

**Comment by nelsonic** [comment]
Ok. So how about we re-visit the Smart Car idea...? hear me out...

## Cheap (_to run and maintain_) Run-about for while we're in PT

I'm not a fan of using my parent's car to get from A-to-B while we are _living_ in PT.
It puts miles on their clock which means they have more maintenance/upkeep and ultimately shortens the useful life of their car (which means they will need to buy a new one sooner...)

By contrast a **smart car** uses **_less than half the fuel**_ of any car either of our families _currently_ own so would thus end up _saving_ us money...!

![smart-car-pt](https://cloud.githubusercontent.com/assets/194400/7742805/8c413c34-ff8b-11e4-8758-56e0c2b846e1.png)

http://www.viamillenio.pt/produtos/Smarts/Smart-Coupe-Passion-CDI-1425640672

**Comment by nelsonic** [comment]
A smart car is: 
- better for the environment (much less fuel)
- easier to drive and park (much smaller than anything else)
- perfect for going to the shops as a pair/couple

Granted it would take a few **_years**_ to justify in terms of the fuel savings _cost-wise_, but the benefit will accrue to the environment _immediately_!

**Comment by nelsonic** [comment]
## Cabrio?

![smart-cabrio](https://cloud.githubusercontent.com/assets/194400/7742971/aa8f7eec-ff8d-11e4-92d9-d89e7e595bd3.png)

http://www.viamillenio.pt/produtos/Smarts/Smart-Cabrio-Passion-CDI-1427712957

€5,250 is £**3,753** at today's exchange rate.
![xe com-5250eur-is-3753gbp](https://cloud.githubusercontent.com/assets/194400/7743012/feb97860-ff8d-11e4-96f5-6d50f8d21049.png)

**Comment by nelsonic** [comment]
Fuel efficiency ... http://www.fuel-economy.co.uk/stats.html
![fuel-efficiency](https://cloud.githubusercontent.com/assets/194400/7743293/3c3c6a46-ff91-11e4-92f3-b8719b8a70c6.png)

If we approach this _logically_ based purely on fuel efficiency, its worth considering a **Toyota Aygo**...
http://www.olx.pt/nf/carros-cat-378/toyota+aygo

Also, toyotas are super reliable and cheap to maintain...

**Comment by nelsonic** [comment]
http://amora.olx.pt/toyota-aygo-2014-9-600-km-iid-475903136

![toyota-aygo-almost-new-12500](https://cloud.githubusercontent.com/assets/194400/7743637/97e38494-ff94-11e4-84b7-b21e90c53a5d.png)

Sure, this is _way_ more than a smart car! 
But its _new_. and my parent's old banger is 13 years old!

**Comment by nelsonic** [comment]
#### Buy New Car for Mom & Dad!! (_which we can use when we go home..._)

I've offered to get a new car for my parents several times...
My mom drives a **2002** Hyundai Matrix:

![hyundai-matrix](http://srv2.betterparts.org/images/hyundai-matrix-06.jpg)

Its **_okay**_ to drive and has relatively good fuel economy...

**Comment by nelsonic** [comment]
## Toyota Yaris or Aygo ?

Good forum discussion: http://www.toyotaownersclub.com/forums/topic/105290-whats-better-aygo-or-yaris/

**Comment by iteles** [comment]
This progressed a little since yesterday :blush: 
To summarize/clarify: Have we now completely discarded the idea of driving to PT?

My only question on buying your mum a new car is: will your mum actually want a Yaris or Aygo? I remember her saying she really likes the bigger cars like the one she has...

**Comment by nelsonic** [comment]
Yeah, I've been on the phone with my dad this morning... she still holds onto the idea of the bigger car...

**Comment by nelsonic** [comment]
How cool would it be to have one of these: http://pazodearcos.olx.pt/kartcross-kinroad-650k-iid-479037752
![kartcross-650k](https://cloud.githubusercontent.com/assets/194400/7745480/5967e5b6-ffa3-11e4-9bb9-526bddc05352.png)

**Comment by iteles** [comment]
:laughing: In the right context, totally cool

**Comment by nelsonic** [comment]
Back to the matter at hand.
If my mom is still keen on the higher car, a VW Tiguan would be a good option:

![vw-tiguan](https://cloud.githubusercontent.com/assets/194400/7745808/cbfc60be-ffa5-11e4-85d5-96bc4966e10f.png)

http://lisboacity.olx.pt/vw-tiguan-1-4-tsi-sport-4-motion-iid-479105672

But... While the Tiguan is nice to drive and has good visibility (higher up than small cars), getting her another 1.4Litre car is of _limited benefit_ in terms of fuel efficiency...

**Comment by nelsonic** [comment]
I'm super un-decided about wether it makes more sense to buy a Yaris (which is more versatile because it has 5 seats!) or a Smart...

![yaris-11900](https://cloud.githubusercontent.com/assets/194400/7746066/8c138264-ffa7-11e4-8425-a2f5b7fe01b9.png)

http://www.caetanoauto.pt/pt/toyota/usados/usado/automovel/14-NR-91/N/2013/TOYOTA/YARIS/1_0+VVT-i+Comfort+P_Style/4/Caetano+Auto+(Barreiro)?cid=8dade686-cb1a-41b0-992d-0c4b8fb64e2b

![yaris-cheaper-in-faro](https://cloud.githubusercontent.com/assets/194400/7746209/78e93912-ffa8-11e4-9bdc-4e3a8b95aab9.png)

**Comment by nelsonic** [comment]
A _massive_ factor to consider is that the Smart is going to be _much_ cheaper to run because **Diesel is 30% cheaper** in Portugal than unleaded: http://www.precoscombustiveis.dgeg.pt/

![petrol-prices-portugal](https://cloud.githubusercontent.com/assets/194400/7746145/18255156-ffa8-11e4-8d07-dab6881b9b8c.png)

Also the Smart is **_automatic**_ so its _easier_ for _anyone_ to hop in and go.

**Comment by nelsonic** [comment]
I'm still attracted by the 4 seats in the Aygo... http://www.olx.pt/nf/carros-cat-378/toyota+aygo/sort,1

http://queijas.olx.pt/toyota-aygo-1-0-sport-pack-mmt-vsc-2007-41-100-km-iid-477914673
![aygo-6500](https://cloud.githubusercontent.com/assets/194400/7746341/5c8f88a6-ffa9-11e4-8338-aacf704dad22.png)

And this one is **_almost new**_: http://leiria-leiria.olx.pt/toyota-aygo-1-0vvti-2013-iid-475218366

![aygo-7700](https://cloud.githubusercontent.com/assets/194400/7746389/c689683a-ffa9-11e4-870b-5dda07fce301.png)

**Comment by nelsonic** [comment]
I had to post this...! Can you imagine my mother driving a RED Car with **_GO FASTER STRIPES**_!!!
http://matosinhos-porto.olx.pt/toyota-aygo-nuerburgring-como-novo-90-000-km-unico-iid-479001904

![aygo-nurburgring](https://cloud.githubusercontent.com/assets/194400/7746495/ad5980a6-ffaa-11e4-88ff-023d007048d2.png)

It _actually_ says **_nürburgring**_ on the wing mirrors:

![nurburgring](https://cloud.githubusercontent.com/assets/194400/7746543/11366e68-ffab-11e4-838d-034cbb3710db.png)

ROFLMAO!!

**Comment by nelsonic** [comment]
Seriously thought, this Aygo is pretty good: http://lisboacity.olx.pt/toyota-aygo-1-0-2008-66-000-km-iid-478727772 4 doors. 4 seats. super low fuel consumption, easy to park and cheap to maintain.

![aygo-6450-2008](https://cloud.githubusercontent.com/assets/194400/7746653/1c3a469e-ffac-11e4-9c16-d84b51f70a58.png)

**Comment by nelsonic** [comment]
Yaris from 2007 has similar Kms on the clock and only slightly more €'s
http://belas.olx.pt/toyota-yaris-1-0-vvt-i-sol-2007-66-000-km-iid-479172796

![yaris-6980-2007](https://cloud.githubusercontent.com/assets/194400/7746735/b9c6e50c-ffac-11e4-81ed-578dd214e69e.png)

**Comment by nelsonic** [comment]
The engine in the Yaris appears to be **_identical**_ to the Aygo. So the only difference is that the Yaris is more spacious in the back...

**Comment by nelsonic** [comment]
Here's a Yaris from 2008 in good condition, 69.500 km on the clock for € 6.290
http://lisboacity.olx.pt/toyota-yaris-1-0-vvt-i-rock-in-rio-08-2008-69-500-km-iid-476735751

![yaris-2008-6250](https://cloud.githubusercontent.com/assets/194400/7746870/cbeba744-ffad-11e4-86b4-cb119a2fa29b.png)

Seems like a no-brainer to me. @iteles thoughts?

**Comment by iteles** [comment]
If it was up to me, I would only drive 'Yarises' for the rest of my life.
I would note that we have a Yaris (with new brakes and a new engine) available to us for 'free' for the whole time we're in PT (however long that may be), so the value needs to be also in something other than just 'so we have a car whilst we're out there' (€6,300 is still _money_ :moneybag:).

**Comment by nelsonic** [comment]
Is it fair to _occupy_ David's Yaris for 6 weeks? He actually _uses_ it.

**Comment by iteles** [comment]
He'll spend a bit more in petrol in his alternatives, but even if we pay him the difference in petrol (which he'll never accept) it won't come to €6.3k.

**Comment by nelsonic** [comment]
True. we could give him €500 for lending us his car...

**Comment by nelsonic** [comment]
@iteles Float the idea with him, please.

**Comment by nelsonic** [comment]
Final one before I get back to _work_!! White 2008 Yaris: http://palmelagare.olx.pt/toyota-yaris-iid-467252519

![yaris-white](https://cloud.githubusercontent.com/assets/194400/7747260/f0bfc868-ffb0-11e4-94fe-f9c4e639c80e.png)

**Comment by nelsonic** [comment]
This is our price range: http://www.olx.pt/nf/carros-cat-378-p-3/toyota+yaris/sort,1

**Comment by nelsonic** [comment]
Quite like the look of this blue aygo: http://povoadesantairia.olx.pt/toyota-aygo-1-0-fantas-08-2008-65-000-km-iid-477542379
![aygo-2008-65k-5750](https://cloud.githubusercontent.com/assets/194400/7788711/56e3b86c-023f-11e5-9e07-47c1d9407231.png)
Yes, its a smaller car... its a backup.

**Comment by nelsonic** [comment]
XC90 in Portugal: http://frossos.olx.pt/volvo-xc90-7-lug-nac-iid-478806264
![volvo-xc90-portugal](https://cloud.githubusercontent.com/assets/194400/7788850/ad170ad2-0243-11e5-89b6-d0801a9f72c4.png)

**Comment by nelsonic** [comment]
I think I might be in love with this White Smart: http://home.standvirtual.com/patoleiacar_visualizar_8319541_carros.html
![awesome-white-smart-car](https://cloud.githubusercontent.com/assets/194400/7788854/cd1c671e-0243-11e5-9456-be8458c51d39.png)

**Comment by nelsonic** [comment]
Think this is the one to go for: http://saojoaodaslampas.olx.pt/toyota-iq-1-0-vvt-i-2-2010-77-000-km-iid-479288486
![toyota-iq-2010-77k-6500](https://cloud.githubusercontent.com/assets/194400/7789564/f8172d36-025d-11e5-94ab-e1fa8ddc2fee.png)

**Comment by iteles** [comment]
We do have an (old) Yaris available to us at no cost (or at €500 if we were feeling generous) or your mum's old car also.
It's up to you as you'll be doing the bulk of the driving and only you can judge whether it's worth €6.5k of usefulness to your parents once we leave as well.

**Comment by nelsonic** [comment]
You're right, David _does_ have a "spare" car he _can_ afford to lend us.
But... 
1. My parents _current_ car is (11 years) old and clunky.
2. I don't like driving a car that has 200k kms on the clock (more can go wrong...) and I certainly wouldn't want my (_someday_!) wife driving something that could break down on the highway or anything less than :star: :star: :star: :star: :star: NCAP rating: http://www.euroncap.com/en/results/toyota/iq/11066
3. If you thought Toyota Yaris 2001 model is nice to drive, the IQ will spoil you for life! (Parks like a dream!) https://www.youtube.com/watch?t=55&v=cB9YKcEtgUQ
4. What is your _brother_ going to use when he's in PT for the last week in July?

**Q**: Is it "_worth_" the £5k we'll have to spend on buying+insuring it?  
**A**: I'd prefer if it was £3k, but when it comes down to it, its the _perfect_ quick-trip car for my parents (school run, shops, meeting) and will be _great_ for us (or the champions) when we are there too. 

My dad wastes _silly_ amounts of time walking to the train station and getting trains.
I would much rather he invested the time in his work!
A micro-car is ideal for someone who needs to get places easily.

If I was down to my _last_ £5k I would _definitely_ "make do" with what ever we can borrow from others.
But, given that I'm not, and I would like my family to have a **_safe, efficient & cheap**_ (_to run_) little run about vehicle, I think it makes sense...

Please, talk me out of it!

**Comment by iteles** [comment]
My brother doesn't drive the Yaris and he's only going to be in Lisbon for one week (if that).

The question is, will your parents actually _use_ the car? Your mum loves her big cars and your dad doesn't seem to keen on using cars in general if he can avoid it.

If you're asking me to talk you out of it, I think you've talked _yourself_ out of this further up already :arrow_up::

> It means we would be spending £5k more than we need to in order to get us from A-to-B!
> If we pay people £10 per hour to work on building the product, that's **_FIVE HUNDRED HOURS__**!!
> Or to put it another way, if a person worked 7h a day for us, 5 days a week (i.e. 35h per week)
> the £5k would be enough to pay a person for **FOURTEEN WEEKS**! :open_mouth:

It also forces you to go back into contracting a few weeks earlier once you take tax into consideration (something to keep in mind, you can do a lot in a month of not contracting!)

**Comment by nelsonic** [comment]
I think I see more potential here... 
anyway. love you! :kiss:

**Comment by iteles** [comment]
Like I said above, so long as the value is "also in something other than just 'so we have a car whilst we're out there', then worth _considering_. Love you!

**Comment by nelsonic** [comment]
Nissan Qashqai +2 http://charnecadecaparica.olx.pt/nissan-qashqai-2-1-5-dci-acenta-2009-90-000-km-iid-480100728
![Nissan Qashqai +2](https://cloud.githubusercontent.com/assets/194400/7981542/96514364-0aa7-11e5-9b2e-49f8cad13ebb.png)
€15,000 is quite expensive for this car... but, it has _Everything_!
The fuel efficient 1.5 DCI engine and the two extra seats!
When I get my next contract in October I might be tempted to get my Mom one of these...

**Comment by nelsonic** [comment]
Meanwhile some great news on the Smart ForTwo front!
This car: http://pt.viamillenio.pt/produtos/Smarts/Smart-Cabrio-Passion-CDI-1427712796
![smart-cabrio-5550](https://cloud.githubusercontent.com/assets/194400/7981673/6b83f0b8-0aa8-11e5-845f-92a00ace84f3.png)

They have confirmed I can get in white at no extra cost!!
![smart-confirmed-any-color](https://cloud.githubusercontent.com/assets/194400/7981680/75253672-0aa8-11e5-9a6c-fccda83c96cd.png)

So I'm _seriously_ considering it for my Dad as a little a-to-b run about...!

**Comment by iteles** [comment]
@nelsonic A note to acknowledge I've read this and have nothing to add to what I've already said :kissing_heart:

**Comment by nelsonic** [comment]
_What is your_ "**_Why...?**_" @iteles

**Comment by nelsonic** [comment]
Renting a Car for two weeks in July:
![holiday-autos-july-2015](https://cloud.githubusercontent.com/assets/194400/8123510/c81bc9ca-10c2-11e5-8161-7a7e3f5323c3.png)

Renting a Car for two weeks in August:
![holiday-autos-august-2015](https://cloud.githubusercontent.com/assets/194400/8123537/461d514a-10c3-11e5-84c5-c6289368c5ee.png)

August is _obviously_ the Peak month so its a bit more expensive...

**Comment by nelsonic** [comment]
http://alcabideche.olx.pt/vw-up-1-0i-take-2012-66-500-km-iid-480647214
![vw-up-7 5k](https://cloud.githubusercontent.com/assets/194400/8316557/c5e0b46e-19ef-11e5-96e3-6ae52d051f4c.png)

> http://www.standvirtual.com/carros/anuncios/VW/Up!/P8399865/ looks _really_ good.
> 
> > http://www.amazon.co.uk/Disney-Sticker-Scene-Up-Pixar/dp/1407560085 :wink:

**Comment by nelsonic** [comment]
The initial clock on the DWYL-mobile

![44jm44](https://cloud.githubusercontent.com/assets/194400/8979774/f006cb9a-36a3-11e5-98bd-9b031b4a1964.jpg)

**Comment by nelsonic** [comment]
![iteles-dwyl-mobile](https://cloud.githubusercontent.com/assets/194400/8980134/5dedb838-36a6-11e5-8ac4-e2debb9debb6.JPG)

**Comment by iteles** [comment]
Can't believe you beat me to it after I told you I was adding this photo! 

![dwyl-mobile-3jul2015](https://cloud.githubusercontent.com/assets/4185328/8980174/9b018880-36a6-11e5-85f8-a4e80773ff5e.jpg)

**Comment by nelsonic** [comment]
Ok. this is pretty much close-able now, right? :wink:

**Comment by iteles** [comment]
Yes!
