### ISSUE TITLE
Honest Slogans ...

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/nelsonic.github.io#105]
Got distracted with this: http://digitalsynopsis.com/advertising/honest-advertising-slogans/ for bit...

**Comment by nelsonic** [comment]
My favourites:
![icloud-parody-logo-hacker-friendls-storage](https://cloud.githubusercontent.com/assets/194400/12005993/6fdb4f5a-abb9-11e5-8aeb-d5b817f1e228.jpg)
![ben-and-jerries-eat-away-your-feelings-parody-logo](https://cloud.githubusercontent.com/assets/194400/12005992/6fdb117a-abb9-11e5-90fa-8ab8337f3024.png)
![mens-health-perfect-abs](https://cloud.githubusercontent.com/assets/194400/12005994/6fde1492-abb9-11e5-87bc-68470af8f4c3.jpg)
![candy-crush-parody-logo](https://cloud.githubusercontent.com/assets/194400/12005996/6ff316a8-abb9-11e5-93fd-8db988425839.jpg)
![hallmark-parody-logo](https://cloud.githubusercontent.com/assets/194400/12005995/6ff1e6ca-abb9-11e5-9623-4a713e8061c1.jpg)
![mabeline-maybe-its-photoshop](https://cloud.githubusercontent.com/assets/194400/12005997/6ff4568a-abb9-11e5-948e-7d567cdfca8a.jpg)
![facebook-logo-procrastination](https://cloud.githubusercontent.com/assets/194400/12005998/700a72a8-abb9-11e5-9019-060028053791.jpg)

**Comment by iteles** [comment]
Ben & Jerry's & Men's Health :laughing:
