### ISSUE TITLE
Oculus?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/nelsonic.github.io#12]
Should we order an Oculus Developer Kit?
https://www.oculus.com/order/

**Comment by iteles** [comment]
If it's a toy, no. 
But I doubt you'd suggest it unless you had a plan to use it to make money :stuck_out_tongue: 
So, if we plan to use it to make money in the next 3-4 months, yes. If it's longer term than that, let's focus for now.

**Comment by nelsonic** [comment]
_Everything_ is a "_Toy_" in the hands of someone who sees it that way.
Conversely, "_everything_" is an opportunity to create value.
It is what you **_`make`_** of it.

**Comment by nelsonic** [comment]
Closing as no longer relevant. 
We will be using Apple's AR kit when the time comes.
