### ISSUE TITLE
Amazon Prime Music has Great Focus/Coding Music [Free with Prime]

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/nelsonic.github.io#140]
If you Download the App: http://www.amazon.co.uk/gp/dmusic/desktop/downloadPlayer/
and login using your Prime-enabled Account you get a great little Focus Music Service! 
![amazon-prime-music](https://cloud.githubusercontent.com/assets/194400/12650377/81dcd31e-c5da-11e5-8e72-391acf1f696f.png)

cc: @iteles :wink:

**Comment by iteles** [comment]
:+1: Was excited by yesterday's email announcement!
