### ISSUE TITLE
File Tax Returns.

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/nelsonic.github.io#141]
![death or taxes](http://frameofmindframing.ca/wp-content/gallery/edd-uluschak/death-and-taxes.jpg)

**Comment by iteles** [comment]
😄

**Comment by nelsonic** [comment]
![hmrc-submit-your-return](https://cloud.githubusercontent.com/assets/194400/12713325/d62c4178-c8c5-11e5-96d5-5103aff266e2.png)
