### ISSUE TITLE
4G Mobile Wi-Fi

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/nelsonic.github.io#219]
TP-Link M7350 http://www.maplin.co.uk/p/tp-link-m7350-4g-mobile-wi-fi-device-a87tc
![maplin-tp-link-m7350](https://cloud.githubusercontent.com/assets/194400/16744147/98fcb16e-47a7-11e6-8f83-a30416301bb0.png)

Given that I have a Maplin Voucher which will expire and we will _use_ a Mobile 4G device in SA/PT ...

Incredibly, its the same price on Amazon! https://www.amazon.co.uk/TP-LINK-M7350-LTE-Advanced-Mobile-Hotspot/dp/B00PFXFWTQ
![m7350-amazon](https://cloud.githubusercontent.com/assets/194400/16744220/039462e2-47a8-11e6-9018-16744f4d4841.png)

**Comment by nelsonic** [comment]
@iteles what do you think? should I stop by Maplin's tomorrow and pick one up to take with us?

**Comment by iteles** [comment]
:+1: That's what the thumbs up was supposed to mean :wink:

**Comment by nelsonic** [comment]
Sorry, I don't get _notifications_ for Thumbs Ups... 😞

**Comment by iteles** [comment]
Ah, of course and they don't show up on github mobile either 😕

**Comment by nelsonic** [comment]
Ok. went past Maplin this morning. they have it in stock. Unless you think we can "get by" with using tethering from one of our phones, I think I'm just going to get one...

**Comment by iteles** [comment]
Definitely get one, there will be times when we will need to be downloading code and using gitter. We need **good** internet in SA.

**Comment by nelsonic** [comment]
Got it. worked well for us in SA. should work well in PT too. ✅
