### ISSUE TITLE
House Boat Investment?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/nelsonic.github.io#225]
While searching for a place to stay/buy I saw this house boat:

![house-boat-listing](https://cloud.githubusercontent.com/assets/194400/17858138/6a141f90-687c-11e6-894d-7137ab8f516b.png)

It's in Canary Warf so would probably be rentable if we moved away ...

![house-boat-transport-links](https://cloud.githubusercontent.com/assets/194400/17858172/86a62612-687c-11e6-8f0d-e8188b2e230a.png)
- Link: http://www.zoopla.co.uk/for-sale/details/39695438
- PDF: [river-boat-london.pdf](https://github.com/nelsonic/nelsonic.github.io/files/430351/river-boat-london.pdf)

On the surface this is quite _underwhelming_ given that the Mooring fees are **£13,176 per annum** or  **_£1,098/month**_ ... 

but, when you inspect the _floor plan_:
![boat-house-floor-plan-main](https://cloud.githubusercontent.com/assets/194400/17858904/7d5b76e0-687f-11e6-98ae-452f034566c3.png)

It becomes apparent that there's quite a lot of _**wasted space**_ on the vessel:
![boat-house-floor-plan-aft](https://cloud.githubusercontent.com/assets/194400/17858945/9b3d9f8a-687f-11e6-983a-db936fef2b66.png)

If we _assume_ that there isn't much point to having a gigantic engine for a boat that will likely _never go anywhere_ ... If we could strip out the engine room and utility room and re-furbish them to be bedrooms we would create a **4.5 bedroom** floating flat for not much more than a 1-bed studio...

Assuming that raising the boat out of the water, removing the engine and refurbishing the two rooms would cost £50k the total investment would be £210k. for a floor-area similar to our _house_!

It would need to have decent "occupancy" to ensure that the Mooring fees were always covered.
##  Further Reading
- http://www.telegraph.co.uk/finance/personalfinance/money-saving-tips/11735888/Living-on-a-houseboat-a-cheap-housing-alternative.html
- http://www.independent.co.uk/property/house-and-home/floating-assets-what-should-you-know-before-you-take-the-plunge-and-buy-a-house-boat-2022216.html
- http://www.ourproperty.co.uk/guides/buying_a_houseboat.html
- http://www.canaljunction.com/boat/liveaboard1.htm
- Older post: https://www.theguardian.com/money/2005/jul/29/personaleffects
- AirBnB London Boat houses: http://www.boatsandoutboards.co.uk/advice/8-best-airbnb-houseboat-and-narrowboat-rentals-in-the-uk-/46

**Comment by nelsonic** [comment]
@iteles if you're prepared to live on a (_totally refurbished with fireplace_) boat for a few months 
This could work: http://www.rightmove.co.uk/property-for-sale/property-55071220.html

![82k-houseboat-london](https://cloud.githubusercontent.com/assets/194400/19693741/7383e9c2-9ad4-11e6-8252-3308cd4e8534.png)

Nice living space:

![house-boat-inside](https://cloud.githubusercontent.com/assets/194400/19693828/e7c6b01c-9ad4-11e6-837d-7c6519e7917f.png)

Real Shower:

![house-boat-shower](https://cloud.githubusercontent.com/assets/194400/19694355/e46517f4-9ad6-11e6-8c9a-32546b88d4f6.png)

## Highlights:
- We can buy the place for `cash` and have `no mortgage`! **_or**_ have a `£400/month` mortgage ...
- We could live on `Regent's Canal`. 
- our living room would be our office. 
- we'd need to use 4G broadband but it's £20/month for "unlimited" 
  ![mobile-4g-broadband-unlimited- 20](https://cloud.githubusercontent.com/assets/194400/19694116/f3c6c298-9ad5-11e6-8312-9c9bb8adcfde.png)
- We'd have _plenty_ of money left over to get [`brompton`](https://www.brompton.com/The-Bike) (folding) bicycles or Electric Mini-scooters: https://github.com/dwyl/phase-two/issues/14 (_which we could charge at "Work"_)

and if you ever get "_sick_" of it we can pass it on to another couple of people who want to save a _bunch_ of money while saving the deposit for a "_real_" house...

> If you're interested/curious, read this `FAQ`: http://www.canaljunction.com/boat/liveaboard1.htm

FYI the Yield is:
![london-1bed-houseboat-yield](https://cloud.githubusercontent.com/assets/194400/19702592/26fd1c1c-9af8-11e6-811f-986b20da6bbd.png)

**Comment by nelsonic** [comment]
Also, for some reason the _original_ Houseboat I looked at a few months back is still on the market and has had it's price reduced: http://www.zoopla.co.uk/for-sale/details/39695438
![2-bed-houseboat-price-reduced](https://cloud.githubusercontent.com/assets/194400/19695277/715f9654-9ada-11e6-96d2-7176e477a3ee.png)

**Comment by nelsonic** [comment]
Recent (November 2013) Published Study: https://www.london.gov.uk/sites/default/files/gla_migrate_files_destination/Moorings%20report%20agreement%20draft%20FINAL.pdf
Backup in case it gets removed: [Moorings-report-agreement-FINAL.pdf](https://github.com/nelsonic/nelsonic.github.io/files/551317/Moorings-report-agreement-FINAL.pdf)

The _important_ bit is page 8 (_the Regent's canal Boroughs map_) which shows that we would need to _move_ every 2 weeks between Hackney, Islington and Tower Hamlets:

![london-canal-boroughs-map](https://cloud.githubusercontent.com/assets/194400/19696947/474c332a-9ae1-11e6-8f1c-13c85326a92c.png)

**Comment by nelsonic** [comment]
[AirBnB for a Houseboat in London](https://www.airbnb.co.uk/s/London--United-Kingdom?page=1&source=map&airbnb_plus_only=false&sw_lat=51.45503073262738&sw_lng=-0.14438022380159055&ne_lat=51.56027412358276&ne_lng=0.029341089674971954&search_by_map=true&zoom=12&property_type_id%5B%5D=8&ss_id=zjdiqaoh&allow_override%5B%5D=&s_tag=LoIdHrv5) is quite decent...
![london-airbnb-houseboat](https://cloud.githubusercontent.com/assets/194400/19697444/43a8bd22-9ae3-11e6-8473-fdefa544c1d1.png)

Obviously we would need to inform people of the _precise_ location of the boat before they arrive, but we _could_ rent it out on weekends and go somewhere else e.g: PT to monitor Phase 2 dev...

**Comment by ghost** [comment]
@nelsonic how comes you decided against a houseboat in the end?

**Comment by nelsonic** [comment]
@markwilliamfirth _great_ question! the _hassle_ of having to move it every 2 weeks and not having "certainty" of our location ... also starting out a House-boat-life going into winter did not appeal to Inês... 😜 
We aren't _totally_ off the idea, but in the _short-term_ being where we are is going to save us a _huge_ amount of time! you should come and visit us on Palmers Road soon to see why it's a _good_ idea. 🖥  📶  ✅

**Comment by nelsonic** [comment]
no longer relevant. closing.
