### ISSUE TITLE
Git/GitHub Error: No user exists for uid 501 / 503 (SOLVED!)

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/nelsonic.github.io#247]
I just tried to `git pull` or `git push` to one of my own repos and got the following error:
```
No user exists for uid 501
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

![git-github-error](https://cloud.githubusercontent.com/assets/194400/20576041/fa533f84-b1b3-11e6-9f89-a7ed65966737.png)

hmm...

**Comment by nelsonic** [comment]
Quitting iTerm and re-starting it worked.

![image](https://cloud.githubusercontent.com/assets/194400/20576098/43dc9dbc-b1b4-11e6-87d1-6bee72bf8af3.png)

**Comment by codiak** [comment]
Thank you for resolving this for yourself and for me as well ✨

**Comment by nelsonic** [comment]
@codiak lol. documenting _everything_ I do is kinda my thing... 😉 
Glad it helped you. 👍

**Comment by cabbage** [comment]
I have to chime in and thank you as well. Found this yesterday morning after a long night and right before a deadline. Thanks a lot!

**Comment by loicbarrault** [comment]
That just helped me too... However, this is a crazy error ... or crazy error message. Thanks!

**Comment by dwillie** [comment]
This also applies for user id 502, at least in my experience.

**Comment by jonathan-soifer** [comment]
I just want to infer that it also applies for user id 503

**Comment by nelsonic** [comment]
@jaysoifer & @dwillie _thanks_ for informing us. 👍

**Comment by sukima** [comment]
Does anyone have any idea why iTerm would do this?!

**Comment by nelsonic** [comment]
@sukima sadly, no indication in application logs ... 😞

**Comment by jdavis-politico** [comment]
Restarting iTerm would have been the last thing I did. Thanks.

**Comment by WhiteR4bbitt** [comment]
I was about to start worrying, why can't I sync my repo! 

Thanks for the easy quick fix :)

This happened when I had a weird "crash" and my iTerm restored itself in its current state, this is when this happened.

**Comment by adamski** [comment]
Can't believe this is the second time I've found this answer. Thanks again :)
