### ISSUE TITLE
When you can afford to buy your dream car... but resist the temptation! and instead focus what's important!

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/nelsonic.github.io#284]
That _feeling_ when you've put in the hours (_years!_) of work 
and you look at your bank account and think:
I can (_easily_) _afford_ to buy my ***dream car***
and go on the _ultimate_ road trip across the world!!

![image](https://cloud.githubusercontent.com/assets/194400/22181292/7ebb00ee-e081-11e6-8ec6-12e0e1bc5bf9.png)

![image](https://cloud.githubusercontent.com/assets/194400/22181130/d2aa9494-e07c-11e6-9b8c-9e14e93492fc.png)

Since I was a kid (_ask @carolrmc_) I've dreamed of having a Porsche 356 Coupé...
As far as I'm concerned it's the most beautiful yet _understated_ automobile. https://en.wikipedia.org/wiki/Porsche_356

Occasionally when driving home from work with my dad as a child,
we would take the _scenic route_ and stop by the Classic Car dealer in Johannesburg
http://www.hamptons.co.za/pages/showroom/?zDispID=zSch_|_Y||zCat1_|_PCatPorsche||zCat2_|_PCatsold
where they had a black 356B in Mint condition... 
I would stand and ~~stare~~ _marvel_ at it through the showroom window...

### "_This is what I will drive in my 30's, I promised myself_".

The 356 wasn't the _most expensive_ car they had by _long_ shot; 
that title was won by their _Lamborghini Countach_! (_the ultimate "**look at me**" car of the 80's!_)
I love the 356 because it's proportions and shape are _perfect_; there isn't a _flat_ panel on it!
the interior is "_basic_" but complete and the engine is a _modest_ air-cooled 1600cc! unlike most italian "_super cars_" which are 4L V8s!

### _A Classic Porsche is a work of art that you can drive!!_

> _I never "understood" why under-18's weren't allowed into the show room...
it always struck me as myopic that the showroom manager wasn't friendly to kids,
surely the kids who are obsessed by classic cars are his future customers...?! 
If I ran a classic car showroom I would give kids a pair white gloves 
and teach them all about the cars!! 
Love your _future customers_ even if you know most of them will never afford your product!
help them to **dream big** and some of them will sign a cheque for you, some day...
but I digress..._

When we went to university these cost around €9k and have _sky-rocketed_ in value since!
If only I'd had _money_ then and bought ten of them in 2002 ... 
would have made a fortune re-selling them now!

### When I turned `28` I could _afford_ one but instead we bought a house. 
(_a prudent investment in a long-term asset, I'm sure you will agree!_)

In 2013 I could once again afford to buy one, 
but instead re-invested the money.
Now I can afford to buy a _few_ of them 
but I think I will `continue` to resist the temptation. 
and re-invest in something _way_ better: https://github.com/dwyl/phase-two

![image](https://cloud.githubusercontent.com/assets/194400/22181279/b04864b8-e080-11e6-8649-5c5bf97da400.png)

> This guy _got_ a 356 as a Graduation present ... 
http://www.wsj.com/video/porsche-356-a-family-car-like-no-other/57A4D88F-D506-4865-8D61-CF26693A38E5.html
a [good friend](https://www.linkedin.com/in/urhammer) of mine also _inherited_ a mint-condition silver 356 
and promptly _sold_ it and got a modern car... 😧 😢 

I _used_ to "_begrudge_" how my "_lucky_" friends (_those who were born into lots'a'money_) 
got cars for their 18th/21st birthday (_some of them **really nice** cars!!_) 
but now I realise how lucky I am that I was born into a "_hard work_" family (_without money!_).

I learned how _frustrating_ it is to be on _minimum wage_ for _years_ 
and never be _able_ to accumulate any savings because _life_ is _expensive_! 
I had the "_crappy_" (_zero-hours_) dead-end jobs where you can be "_let-go_" without notice.
I know what it's like to have to work 3 jobs to get by.
Obviously, I know how lucky I am. I'm not _blind_! https://github.com/dwyl/stars/issues/2
There are _plenty_ of people who can't even get **one** job,
it's practically _selfish_ of me to "_take_" 3 of them...! _Right_...?!

_Anyway_, all this to say that _occasionally_ during my "***pomodoro break***" 
I open mobile.de do a quick search and let my imagination go...
### _It's good to dream!_

[![image](https://cloud.githubusercontent.com/assets/194400/22181631/cde7b71a-e087-11e6-8a60-7111217ce31f.png)](https://youtu.be/xxSKO3Er-Yg)

what `if` we just took a month "off" 
and did a GT-style road trip across Europe in a Classic Porsche...?

<br />

## _So What?!_

I don't _talk_ about my _obsession_ with classic cars to anyone ...
I suspect most "_guys_" would love to own a Classic and go on a road trip. no "_news_" there!

But _today_ when I was doing my search, I got _spammed_ with an advert (_yes, I don't use ad-block!_)
and I felt _compelled_ to write about it...

does anyone `else` see the _irony_ in getting a ["Makers Academy"](https://github.com/nelsonic/nelsonic.github.io/issues/263) advert on this page...? 🤣 

![image](https://cloud.githubusercontent.com/assets/194400/22181082/dd3e4a82-e07b-11e6-9a14-a7ba1ba190e4.png)

Maybe I should _pay_ to attend a `ruby-on-rails` coding bootcamp to get my "dream job"... 🤔 
Or _maybe_ **all learning should be _free_** to _anyone_ 
and there shouldn't be an _absurdly_ high barrier to entry into the Creative Technologies!!

# >> https://github.com/dwyl/the-book

**Comment by nelsonic** [comment]
Stay focussed on the Goal: https://github.com/dwyl/phase-two/blob/master/goal.md
Work the plan: https://github.com/dwyl/start-here
If we _completely fail_ at our mission: https://github.com/dwyl/phase-two/issues/43
We can always buy a Porsche and go on an Epic Road trip around the Mediterranean sea... 🌅

**Comment by nelsonic** [comment]
We _could_ get this one: http://www.autotrader.co.uk/classified/advert/201701111193000
![image](https://cloud.githubusercontent.com/assets/194400/22584678/8c2495ec-e9eb-11e6-8adb-7eb016014e1b.png)

And _drive_ down to Portugal in the Summer ... 😮 
https://youtu.be/YkgkThdzX-8?t=36s

**Comment by nelsonic** [comment]
Or the more ***practical*** "Phase 2" Car: http://www.autotrader.co.uk/classified/advert/201610309281716
![image](https://cloud.githubusercontent.com/assets/194400/22585041/a5d69e34-e9ed-11e6-8266-d7fee43e2199.png)

If we buy it _in_ Portugal it's a _lot_ more expensive (_Thanks to **BREXIT**!!!_):
https://www.olx.pt/carros-motos-e-barcos/carros/volvo/?search%5Bfilter_enum_modelo%5D%5B0%5D=xc-90&search%5Bdescription%5D=1&search%5Border%5D=filter_float_price%3Aasc

**Comment by nelsonic** [comment]
https://www.autotrader.co.uk/classified/advert/201711050967353
![image](https://user-images.githubusercontent.com/194400/39408904-a438cf98-4bd5-11e8-8e8e-f2a1ad3fb5b1.png)
Yes, I _know_ it's a "replica", but it would still be amazing to drive because the chasis is a Porsche 944!
![image](https://user-images.githubusercontent.com/194400/39408911-cac0587a-4bd5-11e8-8d2d-ad4a4b7dacc8.png)
But then again a Porsche 944 might not be the best "donor car" ... 🤔 
https://www.autotrader.co.uk/used-cars/porsche/944
![image](https://user-images.githubusercontent.com/194400/39409137-9d3988dc-4bd9-11e8-9f37-bcd39be28182.png)

This is more like it! 🤣 
https://www.autotrader.co.uk/classified/advert/201803264957431
![image](https://user-images.githubusercontent.com/194400/39408939-1df82928-4bd6-11e8-9909-4b5c23484307.png)
![image](https://user-images.githubusercontent.com/194400/39408949-3937fe20-4bd6-11e8-864a-605f0223d3fe.png)

That was a fun "break". ⌛️ 🍅 
Back to _work_! 👨‍💻

**Comment by carolrmc** [comment]
I don’t like the shape of the 944 tome it’s not a real Porsche. Suppose I’m
tooold fashioned.

**Comment by nelsonic** [comment]
@carolrmc I _agree_, Don't worry, I wouldn't get a 944. 🙄 
I would only get a [356](https://en.wikipedia.org/wiki/Porsche_356) or a [912](https://en.wikipedia.org/wiki/Porsche_912) ... Sadly, the prices are climbing _fast_... 📈 💸 😕 
Gotta invest all the money I have into "Phase 2" for the foreseeable future ... 🌱 🌳 🥑 🍅 🥗
But that's a _good_ thing because the investment will pay off _much_ better than a classic car! 🚗 >> 🏡 
And by the time I have _garage space_ to _store_ a Porsche, I'll buy it with pocket change. 😜 

_Most importantly_, _you_ will have an _awesome_ retirement place with _real_ activities, food & nature!
that will make ["Groenkloof"](https://groenkloof.net/the-villages/george/) look like a prison camp!

**Comment by carolrmc** [comment]
Sounds exciting. What must I do to help?

**Comment by nelsonic** [comment]
@carolrmc as _soon_ as you get back from your SA trip, 🛬 
you should book a _weekend_ in Braga for a _real_ holiday ... 😉 
(_though there might be some sewing involved ..._) 😜

**Comment by carolrmc** [comment]
On Sun, 29 Apr 2018 at 20:47, Nelson <notifications@github.com> wrote:

> <https://github.com/carolrmc>
>
I agree either of those cars is the real thing😜. You’ll have to give me
dates.. we’ll be back on the 15 or 16 August. Will need to have a holiday
after SA, which is never really a holiday in the true sense of the word.
What kind of sewing are you thinking of?

**Comment by nelsonic** [comment]
Don't _pre-occupy_ yourself with the sewing, lol! 
It's only "basic" stuff which I will have mostly figured out by then ...
But you will _enjoy_ it as we'll be making _practical_ things. 👍 
Cool when you get back and have "unpacked" hop on the Train (or drive up if you like) to Braga! 😉

**Comment by carolrmc** [comment]
On Sun, 29 Apr 2018 at 21:04, Nelson <notifications@github.com> wrote:

> Happy to help😘
>

Don't *pre-occupy* yourself with the sewing, lol!
