### ISSUE TITLE
Folding Bike?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/nelsonic.github.io#327]
Today I'm asking the question: should we get a folding bike?
My reasoning is: 
+ Less likely to be stolen because we don't have to lock it outside in "_not so good areas of town_" (_I've had 3 bikes stolen in London_)
+ No stress about where to park it in our building (_the place we currently live has 3 bike spaces and 7 bikes so it's chaos!_).
+ Can use it when we travel for work (_and pleasure_) without having to pay for a "_bike ticket_". e.g: Visiting a client in Oxford or Brighton we can cycle to the train station, hop on the train without worrying about the ticket inspector (_or other passengers_) complaining about a bulky bike (_often you either aren't allowed to bring a bike on the train or they force you to buy an extra ticket!_), then on the other side we just hop on the bike and ride it to the destination.
+ Perfect land-vehicle for [living on a boat](https://www.youtube.com/channel/UCZdQjaSoLjIzFnWsDQOv4ww) ... ⛵️ [`#RemoteWorking`](https://github.com/dwyl/remote-working)
 
> @nogainbar has/uses a Brompton to get to work and seems to love it... 🤔 
(_we know a few other people who have folding bikes and swear by them...!_)
> @jrans got a folding bike last year (_I forget the model_) and the feedback he gave was that he would not go "back" to a "normal" bike. 🚲 
Jack, I know you did a bunch of research for folding bikes last year, but I can't find it online ... 
if you still have your research, please share! thanks! 👍 
> @ZooeyMiller is an experienced bike mechanic and will be able to give us some advice on maintenance costs and difficult for a folding bike. 💸 
> @markwilliamfirth did _extensive_ research on both electric and folding bikes and has a spreadsheet for it. this would make a _great_ blog post BTW Mark... 😉 

## Where do I _start_ Researching this?

+ http://www.bikeradar.com/gear/article/best-folding-bike-buyers-guide-46903
+ https://www.theguardian.com/technology/2015/apr/09/folding-bike-review-brompton-tern-strida-dahon-birdy
+ http://www.independent.co.uk/extras/indybest/outdoor-activity/best-folding-bike-under-500-raleigh-brompton-tern-bobbin-8683766.html
![image](https://cloud.githubusercontent.com/assets/194400/24577340/eb895842-16c3-11e7-80a7-2a57d641a3bd.png)

### Best Folding Bike in 2017 (_someone picked their video title for SEO..._ 😉 )

[![image](https://cloud.githubusercontent.com/assets/194400/24577074/2c1e44bc-16bf-11e7-99f9-219a0c7dd218.png)](https://youtu.be/56yeWGMKTmo "Click to watch!")
https://youtu.be/56yeWGMKTmo

[![image](https://cloud.githubusercontent.com/assets/194400/24576770/179ed312-16ba-11e7-8c92-0f989d8aadc8.png)](https://youtu.be/g5Z0OgaKtpQ "Click to watch!")
https://youtu.be/g5Z0OgaKtpQ
The most recommended bike in this review is the Dahon Vitesse ... hmm ...

But then this comparison video: "**Dahon vs Brompton folding bike**" suggests that the only reason _not_ to get a Brompton over a Dahon is the price:

[![image](https://cloud.githubusercontent.com/assets/194400/24576810/917c5f42-16ba-11e7-96b7-897204a1cade.png)](https://youtu.be/94zohQsDqIA "Click to watch!")
https://youtu.be/94zohQsDqIA
The Brompton is smaller (_folds down to a more compact size_) and lighter (_to carry/transport_).

### More useful videos:
+ Comparison of 26" vs 20" inch Folding Bikes: https://youtu.be/hVakicqbARA

### Benefits:
+ Great for commuting
+ Take it anywhere and not leave it locked up outside
+ Perfect for touring (_honey moon...?_ 😜  )

[![image](https://cloud.githubusercontent.com/assets/194400/24576884/bbe6f886-16bb-11e7-8f93-cf4b4a53b3bc.png)](https://youtu.be/Fp6StexKoEQ "Click to watch!")

### Costs: 
+ Price. (_way more expensive to **buy** than a regular bike or "cheaper" folding bike_)
+ More expensive to maintain & find parts than a regular bike...?

Reason not to get a Brompton:
[![image](https://cloud.githubusercontent.com/assets/194400/24576728/667fd6c6-16b9-11e7-8ba1-6e55a966ddb8.png)](https://youtu.be/xms_ctaVNm0 "Click to watch!")
https://youtu.be/xms_ctaVNm0
This video is _surprisingly_ "_fair_" despite the overwhelming negative response (_comments & down-votes_)

Avoid overpaying:
[![image](https://cloud.githubusercontent.com/assets/194400/24576755/d4a02930-16b9-11e7-9f0b-429c571bb248.png)](https://youtu.be/zsmAS61Hptw)
https://youtu.be/zsmAS61Hptw

I've thought (_dreamt_)  of getting a Brompton for as long as I've known they exist!
If you don't know what they are, watch this:
[![image](https://cloud.githubusercontent.com/assets/194400/24576702/bce557b2-16b8-11e7-91ef-e8053650baa8.png)](https://youtu.be/Lh4yStWFNvs "Click to watch!")

They are _incredibly_ versatile I've seen people using them with bike trailers:
[![image](https://cloud.githubusercontent.com/assets/194400/24576910/31d55556-16bc-11e7-9774-22a4fddc97ad.png)](https://youtu.be/ocMRuUBUFrU "Click to watch!")
https://youtu.be/ocMRuUBUFrU

Found this one White on Gumtree:
![image](https://cloud.githubusercontent.com/assets/194400/24576405/674d3c52-16b3-11e7-8e15-bd5e0c3d304a.png)
https://www.gumtree.com/p/bicycles/brompton-m-type-folding-bicycle/1226696674
Looks like it's in good condition from the photos (_and the description_)

This _exact_ bike costs £1,175 `new`:
![image](https://cloud.githubusercontent.com/assets/194400/24576398/4c1cf922-16b3-11e7-825c-180cb5ad274e.png)
https://www.evanscycles.com/brompton-h6r-2016-folding-bike-EV227819

The ideal Touring (Folding) Bike:
[![image](https://cloud.githubusercontent.com/assets/194400/24576525/2a479bac-16b5-11e7-952a-0c6654f702b0.png)](https://youtu.be/V_1bL__n8y4 "Click to watch!")
https://youtu.be/V_1bL__n8y4

## Further Reading/Research:
+ How to Speak Brompton: https://youtu.be/lmFaQNA9ex0
+ Brompton Bicycles – the unfolding saga of a two-wheeled success story: https://www.theguardian.com/lifeandstyle/2015/apr/17/brompton-bicycles-the-unfolding-saga-of-a-two-wheeled-success-story
+ Travelling with a Brompton and Trailer: https://youtu.be/Fp6StexKoEQ

**Comment by nelsonic** [comment]
Found this "dwyl blue" one on eBay (_so I just bought it on "impulse"_):
![image](https://cloud.githubusercontent.com/assets/194400/24576583/3a92fc08-16b6-11e7-9dea-103b5b2eaa17.png)
http://www.ebay.co.uk/itm/Brompton-Bike-Turkish-Green-M3L-with-two-spare-inner-tubes-good-condition-/401298288518
Less than "perfect" condition ("_a few scuffs_") but still pretty decent.
Map + transport details for this bike:
![image](https://cloud.githubusercontent.com/assets/194400/24576998/a9a410e4-16bd-11e7-8713-f77ac0ca67af.png)
https://www.google.co.uk/maps/dir/2+Palmers+Rd,+London+E2+0SX/Albert+Rd,+London+E10+6PB

Going to collect it this afternoon. 😮

**Comment by nogainbar** [comment]
@nelsonic omg YES! its the best investment you will ever do!! I love my Brommies and wouldnt exchange it for any other bike!!! <3

you gonna love it!

**Comment by nogainbar** [comment]
+ electric bikes I ok but super heavy and also cut all the fun away from exercising your beloved body!! I am not a fan...

**Comment by nelsonic** [comment]
@nogainbar I'd never ridden one before today.
But went for it and loved it!
![img_5528](https://cloud.githubusercontent.com/assets/194400/24580479/82450dda-1700-11e7-8a7a-5c137595b0ba.JPG)
❤  ✅

**Comment by nogainbar** [comment]
@nelsonic amazing! You should also get one of these http://www.nycewheels.com/brompton-eazy-wheels.html
Makes rolling the bike after its folded like butter on toast!
With the wrack, even better!

**Comment by nelsonic** [comment]
@nogainbar also there is http://www.nanoelectricbikes.co.uk which means we can "retrofit" a wheel motor to the Brompton and make it an ***e-bike***! 😮 
Coupled with a 22ah battery pack: http://www.tracerpower.com/12v-22ah-lithium-polymer-battery-pack.html could get a range of **85miles** @ 15mph 😉

**Comment by nogainbar** [comment]
@nelsonic thats called CHEATING! 😜 👻

**Comment by nelsonic** [comment]
Cheating? 😆 
Maybe in London. 👍 
But if you're crossing an ([_Asian_](https://www.google.co.uk/maps/dir/Ho+Chi+Minh+City,+Ho+Chi+Minh,+Vietnam/Kuala+Lumpur,+Federal+Territory+of+Kuala+Lumpur,+Malaysia)) country on your bicycle, 
you might _occasionally_ want some "_assistance_" going up a hill... 😉

**Comment by nelsonic** [comment]
Folding bike acquired. ✅ 
Next step: get good at _riding_ and folding/unfolding it! 😉
