### ISSUE TITLE
Order *NEW* Panniers?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/nelsonic.github.io#35]
@iteles these are _slightly_ more expensive than the ones I got last year... but I think they are _worth_ it for the added visibility...
<img width="975" alt="ortlieb-back-roller-high-visibility-pannier-pair" src="https://cloud.githubusercontent.com/assets/194400/10097995/718cbe6a-6375-11e5-94c8-4873f393c055.png">
Any objections to me ordering a pair?

http://www.evanscycles.com/products/ortlieb/back-roller-high-visibility-pannier-pair-ec106290

relates to: #34

**Comment by nelsonic** [comment]
Or these: http://www.wiggle.co.uk/ortlieb-back-roller-plus-panniers-1/  specifically the green ones:
<img width="1004" alt="green-pannier" src="https://cloud.githubusercontent.com/assets/194400/10100733/a475a312-638b-11e5-8eb9-238691470aa1.png">
which are not high-viz... but I _really_ like them.

**Comment by iteles** [comment]
@nelsonic I like the green ones, they're different enough that we can recognise them as our (and cover them in some high viz strips for good measure if we need to).

**Comment by nelsonic** [comment]
Ordered them. they ended up costing a bit more. :disappointed:
