### ISSUE TITLE
Maslow Hierarchy of Needs > Sleep

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/nelsonic.github.io#36]
http://www.huffingtonpost.com/david-sze/maslow-the-12-characteris_b_7836836.html

**Comment by nelsonic** [comment]
_Forget_ Self Actualisation till you **focus on _Sleep_**!
http://www.npr.org/2015/04/17/399800134/why-do-we-need-sleep
got there from here:
http://www.npr.org/programs/ted-radio-hour/399796647/maslows-human-needs

**Comment by iteles** [comment]
Heard this podcast only yesterday!

**Comment by nelsonic** [comment]
@iteles you _heard_ it but didn't _recommend_ it... 
I've had it downloadeded for _ages_ but only decided to listen to it today...
