### ISSUE TITLE
kitten

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/nelsonic.github.io#379]
Today we found a kitten alone ...
![kitten-abandoned](https://user-images.githubusercontent.com/194400/28547655-cbcb5efc-70c7-11e7-9303-9b31dc26b6e5.JPG)

We knocked on the doors of the houses around where the kitten was 
to find out if anyone knew if the mother had abandoned it
and waited to see if the mother would return ... 

I made the decision to bring the kitten home because it was crying 
and the stray dogs roaming the area were _sure_ to hear/find it ... 
I didn't think it would _survive_ much longer alone.

It weighs 120g:
![kitten-weight](https://user-images.githubusercontent.com/194400/28547665-db929472-70c7-11e7-84eb-047271cc9023.JPG)

And is _very_ small:
![kitten-size](https://user-images.githubusercontent.com/194400/28547681-e4353a80-70c7-11e7-9f3a-c5fedd392fd9.JPG)

Read a bunch of articles:
+ http://www.animalalliancenyc.org/wordpress/2013/05/what-to-do-and-not-do-if-you-find-a-newborn-kitten/
+ https://kittenrescue.org/2017/03/recipes-emergency-kitten-formula/
+ https://kittenrescue.org/2017/03/kitten-care-basics/
+ https://www.thespruce.com/fading-kitten-syndrome-555165
+ http://bestfriends.org/resources/bottle-feeding-kittens
![image](https://user-images.githubusercontent.com/194400/28547518-228b965e-70c7-11e7-8b1a-a5281b6ce42a.png)

I estimate that the kitten is between 8 - 14 days old as it's eyes are open but it's still very weak/light.
We haven't given it a name yet.
But going to the vet in town tomorrow seek advice.

**Comment by nelsonic** [comment]
I _suspect_ that the kitten is/was the "_runt_" of the litter and was not being looked after by the mother (_who may have had too many in the litter to care for..._) 120g is "_skin-and-bone_"
Watched:
![image](https://user-images.githubusercontent.com/194400/28548219-a203a496-70ca-11e7-916c-0abd09ba6448.png)
https://youtu.be/8JJYBHgtlgc
The prognosis isn't great. 😞

**Comment by nelsonic** [comment]
_Apparently,_ there is No shortage of "free" kittens in this area:
![image](https://user-images.githubusercontent.com/194400/28561556-d3c66710-7116-11e7-9e7c-ffa97b363443.png)
http://www.custojusto.pt/braga/animais-domesticos/dao-se-gatinhos-23581761

**Comment by iteles** [comment]
So she survived and no longer needs a mother's milk. #win

We now need to decide whether we _can_ keep her or whether we need to find another home for her.

**Comment by nelsonic** [comment]
@iteles what is the _criteria_ (_that needs to be met_) for _keeping_ the kitten?

**Comment by iteles** [comment]
I suggest: 
+ Amount of time required to look after kitten (and do we have that kind of time)
+ Someone to look after the kitten when we head back to the UK in October
+ Understanding of associated costs (affordability)
+ Agreement on where kitten/cat will be allowed and where it won't so that I have some allergy-free safe havens to retreat to

**Comment by iteles** [comment]
We've been asked to pick her up tomorrow so we need to make this decision today so that we know whether to purchase a way of transporting her, food and a place to sleep.

**Comment by nelsonic** [comment]
Answers to above questions:
+ Time required 5 - 10 mins per day to "look after". (_e.g. feeding and litter box changing_)
+ We can ask my Mom or Bina to look after the kitten when we're in UK
+ Costs €0.30/day (€10/month) dependent on type of food e.g: https://www.lidl.co.uk/en/Products.htm?articleId=1468
![image](https://user-images.githubusercontent.com/194400/29490084-9cb3c94e-8529-11e7-9792-d612800597d8.png)
+ Cat should live outdoors (_given that you are [allergic](http://www.nationalgeographic.com.au/australia/queensland-researchers-may-have-found-a-cure-for-allergies-and-asthma.aspx) ..._) that will be fine in Braga where there is Lots of outside space.

Longer term: we don't know what the future holds. The Cats around Gerês (_where we found the kitten_) seem to survive alright. So we could _easily_ buy €50 of cat food from Lidl (_enough for a few months_) and ask Bina to open one "package" each day for the kitten while we are away.

_Obviously_ this situation is not "_ideal_". 
(_I would prefer the Kitten to live in Gerês where she was born and where we found her ..._)

But I think it's _preferable_ to one of the other suggestions from a person who will remain anon: 
who told us to "_drown it_" ... 
I think cats are _good_ for the local area as they keep _other_ pests in "check". 
It's just a _shame_ that we don't _live_ here (_in PT_) because then this would be _simples_!

**Comment by nelsonic** [comment]
"***Nala***" as a kitten sleeping on my chest while I read in the sunshine last summer:
![image](https://user-images.githubusercontent.com/194400/52368412-3febb500-2a46-11e9-8ab2-a5c1dedf0071.png)

![image](https://user-images.githubusercontent.com/194400/52368590-b688b280-2a46-11e9-8904-dc371b7b1b10.png)

![image](https://user-images.githubusercontent.com/194400/52368647-d4eeae00-2a46-11e9-83d1-4cfd58086923.png)

Pair-programming with my Parrot:
![image](https://user-images.githubusercontent.com/194400/52369329-614da080-2a48-11e9-87cb-b0ed9b313c36.png)

Lap nap time:
![image](https://user-images.githubusercontent.com/194400/52368683-edf75f00-2a46-11e9-88c7-b1c8c6759a30.png)

Inês' hands are _lovely_ 😍 and the kitten is cute _too_:
![image](https://user-images.githubusercontent.com/194400/52368808-36af1800-2a47-11e9-9939-fadc184c0f1f.png)

And now fully grown adult cat laying on my leg while I attempt to get work done on my laptop:
![img_6314](https://user-images.githubusercontent.com/194400/52368240-de2b4b00-2a45-11e9-8035-6c0a067a088d.JPG)

I made her a "pool view" perch at Mom's house:
![image](https://user-images.githubusercontent.com/194400/52368958-855cb200-2a47-11e9-9a78-6d030d02a16d.png)
Where she can get _plenty_ of sunshine and take naps when she's tired:
![image](https://user-images.githubusercontent.com/194400/52368913-7249e200-2a47-11e9-8296-0b84c7707dda.png)

Mom & Nala seem to get get on quite well:
![image](https://user-images.githubusercontent.com/194400/52369039-b0df9c80-2a47-11e9-9e90-663fb7da3db5.png)

Playing with the overhead wooden seagull in the lounge:
![image](https://user-images.githubusercontent.com/194400/52369094-c94fb700-2a47-11e9-9711-ea1c19dde1e5.png)

Learning Chess:
![image](https://user-images.githubusercontent.com/194400/52369218-1469ca00-2a48-11e9-94bd-e87a4ebaeb98.png)


Sitting on Clarice's lap in front of the fireplace:
![image](https://user-images.githubusercontent.com/194400/52369121-dd93b400-2a47-11e9-8437-e40448fee9ab.png)

Helping Clarice do her mobile e-commerce shoping:
![image](https://user-images.githubusercontent.com/194400/52369167-f9975580-2a47-11e9-8fe7-17dfe3065f7f.png)


I'm really a "dog person", but I also, _love_ cats. ❤️

**Comment by iteles** [comment]
I didn't really know where to put this article, but seeing as this issue mentions you're a dog person:
https://www.nytimes.com/2019/09/25/us/labradoodle-creator-regret.html

I had no idea about this! Sucky! Just have to be very careful we know the provenance of a dog if we buy one (I'm in favour of adopting an abandoned one)

**Comment by nelsonic** [comment]
@iteles good article (_thanks for sharing_). Dog breeding is a famously "tricky" subject. 
(_they're basically all genetically weak [inbreds](https://en.wikipedia.org/wiki/Inbreeding#Domestic_animals)_ ... _my parents bread [bulldogs](https://www.google.com/search?q=bulldog+puppy&tbm=isch) before we were born..._)

I don't think I will ever _buy_ a dog. As much as I love Labradoodles ... 
bigger dogs are _terrible_ for the environment. 😞 
https://www.theguardian.com/global/2018/jun/26/pet-food-is-an-environmental-disaster-are-vegan-dogs-the-answer

Yes, cats are carnivores too, so there's an impact. But cats consume an order of magnitude less food.
Nala's favourite pet food is the fish one and she has less than **50g/day**.
By contrast Django (_adult golden retriever_) consumes at _least_ ***500g/day***. 

![image](https://user-images.githubusercontent.com/194400/66125201-3f5bec00-e5de-11e9-8861-5f359cf824ea.png)

https://www.petmd.com/blogs/nutritionnuggets/dr-coates/2015/july/are-you-feeding-your-dog-right-amount-32905

I think it's fair to say that Nala (_a rescue_) has brought a lot of Joy into my parents' lives ...

![image](https://user-images.githubusercontent.com/194400/66125303-80540080-e5de-11e9-9cf6-0d6de677c5b4.png)

`#Pixel3NightMode` [😉](#31)
