### ISSUE TITLE
XCode is a Beast!

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/nelsonic.github.io#408]
The XCode app is _already_ 11 Gigabytes:
![xcode-app-11 3gb](https://user-images.githubusercontent.com/194400/30877098-8ccbcde4-a2f0-11e7-9bc9-c7dc7a2942be.png)

First time I tried to update it I got:
![app-store-we-could-not-complete](https://user-images.githubusercontent.com/194400/30878256-3058218a-a2f4-11e7-802e-b5bb424e713d.png)
So I had to _delete_ some files (_music_) to make space for it!!

And installing the latest update is another **5.39GB**:
![image](https://user-images.githubusercontent.com/194400/30877067-6bdad878-a2f0-11e7-81ec-f7bbef90e245.png)

It's _almost_ as if Apple are _deliberately_ making their IDE/SDK _bloated_ to _force_ people with _older_ laptops to buy a newer computer!

**Comment by nelsonic** [comment]
6h to download the update ... 😮 
Imagine how people on _terrible_ internet connections feel each time they see there's an Update from Apple ... 😞

**Comment by nelsonic** [comment]
_Obviously_ it _failed_: 
![image](https://user-images.githubusercontent.com/194400/30905008-8112a5d8-a36b-11e7-8f9e-a147893de228.png)

😞 

... re-starting the download. (_but now **everyone** is in the office so it will take **much** longer!_)

**Comment by nelsonic** [comment]
10 hours ... ⌛️ 😩 
![image](https://user-images.githubusercontent.com/194400/30905282-49a6e40a-a36c-11e7-99c2-97b94a18f82c.png)
good thing I've got a _12_ hour work day ahead of me! 🙄

**Comment by nelsonic** [comment]
***Eighteen Hours***... 😕 
![image](https://user-images.githubusercontent.com/194400/30905784-c575bf7e-a36d-11e7-9ec4-c3428361b2ac.png)

**Comment by nelsonic** [comment]
Now it says it will take _more_ than a _day_:
![image](https://user-images.githubusercontent.com/194400/30905846-fd19180e-a36d-11e7-8d91-c504fc91dcdb.png)
_Imagine_ trying to download this on a "_rural_" internet connection...?
Apple is systematically _discriminating_ against people (_thinking of building iOS apps_) in "Developing Countries"...

**Comment by nelsonic** [comment]
The morning rush of standup calls has passed so the bandwidth has improved:
![image](https://user-images.githubusercontent.com/194400/30910014-138170ca-a37b-11e7-8b3e-b96ff93523d4.png)

But _not_ holding my breath as the lunchtime cat videos deluge is about to start ... 🙄

**Comment by nelsonic** [comment]
Calculating ...
![image](https://user-images.githubusercontent.com/194400/30919570-ad6e1b52-a399-11e7-8487-9c3cac35dfcb.png)

**Comment by nelsonic** [comment]
Anticipation ...
![image](https://user-images.githubusercontent.com/194400/30919715-209c35be-a39a-11e7-8964-d22fb34c347b.png)

**Comment by nelsonic** [comment]
No thanks ...
![image](https://user-images.githubusercontent.com/194400/30957588-fb7ca308-a43a-11e7-9acf-c2e5756495ce.png)

**Comment by nelsonic** [comment]
Apple de-activated my developer account ... and now I cannot re-activate it. 😞 
![image](https://user-images.githubusercontent.com/194400/30978078-c2755886-a479-11e7-939c-75711e2e86ed.png)

**Comment by nelsonic** [comment]
Continue: https://developer.apple.com/xcode/

**Comment by nelsonic** [comment]
Apparently my credit card expiring is a "_reason_" for Apple to lock my out of my account ...
![apple-account-recovery](https://user-images.githubusercontent.com/194400/30983134-d437d764-a489-11e7-8e11-713698eddb17.png)
Thanks Apple ... 😠 
Not like I have any _work_ to be doing ...

**Comment by nelsonic** [comment]
Next: https://iforgot.apple.com/password/verify/appleid

**Comment by iteles** [comment]
What a saga.

**Comment by nelsonic** [comment]
Still waiting ...
![account-recovery](https://user-images.githubusercontent.com/194400/31335820-2a2af9f2-acec-11e7-9a78-c44f52a52b1d.png)

**Comment by nelsonic** [comment]
Installing "_additional components_" ...
![image](https://user-images.githubusercontent.com/194400/31335911-82b16700-acec-11e7-8fdc-98abe7340b4c.png)

Eventually: 
![image](https://user-images.githubusercontent.com/194400/31335965-c3964272-acec-11e7-8ba6-4182fdd6f838.png)

**Comment by nelsonic** [comment]
Oh Xcode ... 
![image](https://user-images.githubusercontent.com/194400/31853639-b3f159ce-b683-11e7-897e-c1967737fba7.png)
days after I updated to the latest version Xcode has an update that requires me to "make space" on my hard disk again ... 🙄

**Comment by nelsonic** [comment]
Another 1.28 GB ...
![image](https://user-images.githubusercontent.com/194400/32236680-c6386d78-be5a-11e7-9569-c2c10dae20d5.png)

very "developing-nation" internet connection friendly ... 🙄 
thanks apple! 👍

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/33239252-c37e5d00-d295-11e7-8341-05b3b33c0a5b.png)

![image](https://user-images.githubusercontent.com/194400/33239247-b975e4ae-d295-11e7-94c5-cbbf941a9822.png)
latest XCode update 6.73 GB of _additional_ free space required...

**Comment by nelsonic** [comment]
This is getting a bit _tedious_ now ...
![image](https://user-images.githubusercontent.com/194400/33538804-4368fc52-d8bb-11e7-862b-5eeb252590db.png)
Apple are basically _forcing_ me to upgrade the storage on my Mac just so I can use XCode ...
And the _Only_ reason I need Xcode is for React Native (Client) Projects which should not have been built as "Native" apps in the _first_ place!!

**Comment by nelsonic** [comment]
The _reason_ I don't have "enough" space to download XCode is because Apple downloaded **4.9 GigaBytes** of "**Install macOS High Sierra.app**" to my machine _without_ my consent!
![image](https://user-images.githubusercontent.com/194400/33605331-34132d08-d9b1-11e7-83ab-93f700d4e3f5.png)

macOS High Sierra, the OS with the Massive Security Vulnerability http://www.bbc.co.uk/news/technology-42166438

**Comment by nelsonic** [comment]
Yay! Another ***2.91 GB*** of cruft on my Computer ...
![image](https://user-images.githubusercontent.com/194400/33609288-7028b2c8-d9bf-11e7-9742-be79e0c84e8e.png)
_Thank You, Apple_!
![image](https://user-images.githubusercontent.com/194400/33605936-98193fb6-d9b3-11e7-834a-d8965365f241.png)
