### ISSUE TITLE
Team Mark (LinkedIn Recommendation)

### ISSUE THREAD

**Issue by ghost** [nelsonic/nelsonic.github.io#423]
Moved from: https://github.com/dwyl/hq/issues/8

**Comment by nelsonic** [comment]
@markwilliamfirth is your domain/DNS still active?
![image](https://user-images.githubusercontent.com/194400/32090768-c72a0552-baf9-11e7-885c-bac2ebb4f307.png)

Might be something to do with the _internet_ of where I am.

Also, you aren't showing up in my LinkedIn Auto-complete or Search Results ... 😞 
![image](https://user-images.githubusercontent.com/194400/32090855-324604ee-bafa-11e7-9911-ed98ea14f65e.png)

Works when I _Google_: https://www.google.com/search?q=mark%20william%20firth
... https://www.linkedin.com/in/markwilliamfirth

Let me know you want something _specific_ to Operations in Startups or _generic_. 👍

**Comment by ghost** [comment]
@nelsonic the markwilliamfirth.com domain isn't active anymore and you might not be able to find me via that search on LinkedIn search because I changed my name to "Mark W. Firth"

**Comment by nelsonic** [comment]
@markwilliamfirth your website was _amazing_! 
it was one of the _best_ examples of personal site! 😍 
Bring it back! 🔙 
[![image](https://user-images.githubusercontent.com/194400/32132443-73d0f880-bbbb-11e7-8942-f797f6a63da7.png)](https://youtu.be/N2ICtCO8TCw "Back for good...")

`Mark W. Firth` fair enough, it's _shorter_. 👍

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/175770337-fee654aa-faaf-426e-b09e-9da97ca93eb5.png)

# 🤷‍♂️

**Comment by nelsonic** [comment]
Re-brand apparently:  https://www.linkedin.com/in/maxxturing/ 💡

![image](https://user-images.githubusercontent.com/194400/175772094-097ca99a-11a3-4942-803a-7013b51d5dd5.png)

I mean, if you can pick your own name. Might as well pick a great one! 😜
