### ISSUE TITLE
Laser Cutting Machine

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/nelsonic.github.io#455]
https://www.alibaba.com/product-detail/Shenzhen-Triumph-Metal-cutting-Stainless-steel_60487641276.html
![image](https://user-images.githubusercontent.com/194400/37718165-008ce854-2d1a-11e8-92b3-2f783209a939.png)

Spec:
![image](https://user-images.githubusercontent.com/194400/37718241-2db108c4-2d1a-11e8-9dc0-7477c0344877.png)

![image](https://user-images.githubusercontent.com/194400/37718320-55e1cb58-2d1a-11e8-9888-b5ab1c7027a2.png)
I'm concerned about the ***weight***: "3300KG" as I won't be able to _move_ it without an industrial fork-lift ... 😕 

Sent enquiry via Alibaba Message:
![image](https://user-images.githubusercontent.com/194400/37868449-59506dea-2f9e-11e8-8907-d3571e23cf41.png)

**Comment by nelsonic** [comment]
https://makezine.com/2015/12/02/a-guide-to-buying-your-first-laser-cutter/

**Comment by nelsonic** [comment]
http://hpclaser.co.uk/index.php?main_page=product_info&cPath=1&products_id=42
![image](https://user-images.githubusercontent.com/194400/37718700-3ad5988e-2d1b-11e8-97d4-048c1f2b8390.png)

**Comment by nelsonic** [comment]
The _ultimate_ laser cutter machine is "Trotec" ... (_often referred to as the "Rolls Royce" of lasers_)
https://www.troteclaser.com/en-gb/trotec-laser-machines/laser-cutters-sp-series
![image](https://user-images.githubusercontent.com/194400/37867585-d411058c-2f92-11e8-82dd-cb117d207500.png)

Detail: https://www.troteclaser.com/fileadmin/content/images/Laser_Machines/SP_Series/SP-series-laser-cutter.pdf

_Obviously_ they don't have prices on their website ... 🙄 
So I sent them a request:
![image](https://user-images.githubusercontent.com/194400/37867591-f493f3dc-2f92-11e8-8e85-2c74f58dbecf.png)

I _strongly_ suspect that the price will be the cost of a _house_ 
given that a _refurbished_ 300mm machine is $15K:
![image](https://user-images.githubusercontent.com/194400/37867606-2f9d3ad8-2f93-11e8-82ab-2c440994a0f0.png)

**Comment by nelsonic** [comment]
Found this on ebay which appears to be good:
https://www.ebay.co.uk/itm/Rose-Graphix-4x8-Flatbed-Laser-Cutter-Engraver-150W-CO2-52-x100-1-yr-WNTY-USA/151828433215
![image](https://user-images.githubusercontent.com/194400/37867713-36202504-2f94-11e8-9f1c-8e7454654521.png)
![image](https://user-images.githubusercontent.com/194400/37867922-446be226-2f97-11e8-8e1b-3c5878e3e957.png)

Their website lists it _slightly_ cheaper:
https://bescutter.com/collections/lasers/products/industrial-level-52x100-co2-laser-cutter-100w-to-150w
![image](https://user-images.githubusercontent.com/194400/37867983-d4f33bd2-2f97-11e8-8813-5cee33c17ab6.png)

Sent enquiry about postage to Portugal. 📩 


They also sell a _Fibre_ Laser:
https://bescutter.com/collections/lasers/products/industrial-fiber-laser-metal-cutter-300w-to-1200w-52-x-100
![image](https://user-images.githubusercontent.com/194400/37868140-0bcc457a-2f9a-11e8-90e4-107783b5dd81.png)

This is a _really_ insightful video which shows just how _big_ the Fibre laser machine is ... 😮 
[![image](https://user-images.githubusercontent.com/194400/37868130-cc0d89f8-2f99-11e8-8416-1b5b820ee963.png)](https://youtu.be/nmBxwyo1QSE)
https://youtu.be/nmBxwyo1QSE

**Comment by nelsonic** [comment]
The Boss Laser HP-5598 looks _really_ good:
https://www.bosslaser.com/boss-ls-5298.html
![image](https://user-images.githubusercontent.com/194400/37868383-3aa8c442-2f9d-11e8-8134-96dd49d0b63b.png)
![image](https://user-images.githubusercontent.com/194400/37868388-456ddde0-2f9d-11e8-8696-c2cb1c42e65f.png)

Of _particular_ not is the "FREE Lifetime Tech Support".
**$26,488.00** is more "_expensive_" than the "Rose Graphix" model above,
but I suspect the _product_ is worth it.

**Comment by nelsonic** [comment]
https://www.icontainers.com/quotes/FCL/USSAV/PORT/US/PTOPO/PORT/PT/?dv20=1&dv40=0&hc40=0&freight=true&include_origin_charges=false&include_destination_charges=false&first_quote_id=3282948
![image](https://user-images.githubusercontent.com/194400/38143147-1826a59e-3437-11e8-92ab-6418ee7e1684.png)

**Comment by nelsonic** [comment]
https://www.icontainers.com/quotes/FCL/USSAV/PORT/US/PTOPO/PORT/PT/?dv20=1&dv40=0&hc40=0&freight=true&include_origin_charges=false&include_destination_charges=false&first_quote_id=3282948
![image](https://user-images.githubusercontent.com/194400/38143147-1826a59e-3437-11e8-92ab-6418ee7e1684.png)

**Comment by nelsonic** [comment]
This type of design is _only_ possible with a Laser Cutter:
![image](https://user-images.githubusercontent.com/194400/41501691-0ef0403c-71a1-11e8-984d-cf36a70ec8c1.png)
http://www.core77.com/projects/43929/Aviator-Chair-A-Flat-Folding-Leather-Chair-Made-Using-No-Joinery

**Comment by nelsonic** [comment]
If the objective is to cut ***metal***, then a Plasma cutter might be a better option:
http://www.cncrouterparts.com/pro-cnc-plasma-kit-p-444.html
![image](https://user-images.githubusercontent.com/194400/52468906-f7d1ad00-2b81-11e9-97d5-649069e806b7.png)

[![image](https://user-images.githubusercontent.com/194400/52469071-5d259e00-2b82-11e9-9361-53e376abba04.png)](https://youtu.be/nz_1wMBvI58)
https://youtu.be/nz_1wMBvI58

**Comment by nelsonic** [comment]
https://3doutlet.shop/collections/gravadores-a-laser/products/maquina-de-corte-gravacao-a-laser-1300x2500mm
![image](https://user-images.githubusercontent.com/194400/68204006-fa511e00-ffbe-11e9-88f5-9e8a046c2945.png)
![image](https://user-images.githubusercontent.com/194400/68206788-7ea69f80-ffc5-11e9-8fe4-285b9f4075b7.png)


https://www.alibaba.com/product-detail/Widely-Used-Fabric-And-Wood-60_62233536532.html
![image](https://user-images.githubusercontent.com/194400/68203956-df7ea980-ffbe-11e9-91b0-a615064642d5.png)

I'm a bit undecided about using a Laser Cutter for Woodworking for two reasons:
1. Lasers _burn_ the sides of the wood during the cutting process.
2. It reduces the designs I am able to create to 2D with right-angle edges.

This is a good post on comparing th 
https://oshkoshdesigns.com/modern-woodcutting-cnc-routers-vs-lasers

**Comment by nelsonic** [comment]
Just came across this competition on Instructables:
https://www.instructables.com/contest/furniture2019
![image](https://user-images.githubusercontent.com/194400/68236620-68b4d100-fffd-11e9-9287-4552a6da724f.png)

I'm sure that by the time our Laser cutter arrives there will be plenty of entries, but let's check back and see. 💡

**Comment by iteles** [comment]
@nelsonic If we're able to get the confirmation of the order to him soon, Samir should be able to place the order tonight (i.e. before morning in China).

Personally, I would go for the 180W machine over the 150W or 130W. 

The advantage of having things cut after one pass outweighs the additional cost in my view, but I _would_ insist on 10 hours of support thrown in there too at the price we are being quoting.

The only disadvantage I see is the lower dpi on detailed engraving (200 dpi) but that's still relatively detailed and I don't imagine we'll need THAT much more than this on a regular basis.

**Comment by nelsonic** [comment]
@iteles it appears that having a 180W _might_ mean that we can't do "delicate" work because the CO2 laser cannot be run at less than 10% of full output. see this thread:
https://sawmillcreek.org/showthread.php?222774-Specifically-what-s-the-difference-in-60-80-and-100-watts-chinese-laser-machine
It's not just a "lower DPI" it's that the _intensity_ of the laser might be too high and thus it will _obliterate_ the material we are attempting to engrave ... we can always _test_ it and if the 180W is "too strong", we can get a lower wattage bulb. 💭 

Given that the **`main` purpose** of this machine is to **cut** our [**furniture**](https://github.com/dwyl/home/tree/master/furniture) for [@home](https://github.com/dwyl/home), I am inclined to _agree_ that cutting the **15mm Plywood** in a **_single_ pass** is _preferable_ to _multiple_ passes with the 130W tube.  

Our **`main` objective** is getting the furniture made ASAP.
Given that I've calculated 200h (_or 4 weeks of machine time_),
it's probably wise to not need to _double_ it by having to do two passes for each cut. 💭 

Email copy proposal:

```
Olá Samir,

Depois de conversarmos decidimos que queremos avançar com a compra da
Máquina de Corte/Gravação a Laser 1300x2500mm 
com o upgrade do tubo e fonte de alimentaçao para os 180W.

Se nos poder enviar um orçamento com o preço final,
poderemos efectuar a transferencia bancaria.

Muito Obrigado,
Nelson
```

Feel free to edit this email copy directly.
LMK when you think it's OK to send. 
Thanks.

**Comment by iteles** [comment]
@nelsonic Done! Please insert the correct dados de facturação (MDC address).

**Comment by nelsonic** [comment]
# Sent ✉️ ✅ 
<img width="912" alt="Laser-order-email-sent" src="https://user-images.githubusercontent.com/194400/68411797-0b4a8c80-0183-11ea-8fd1-cf51f298fd19.png">

**Comment by nelsonic** [comment]
Received invoice:
<img width="1237" alt="Screenshot 2019-11-08 at 18 04 41" src="https://user-images.githubusercontent.com/194400/68499925-639c8f80-0252-11ea-8051-c4c58cd476bf.png">

Sent the _mountain_ of cash:
<img width="1256" alt="paid-for-laser" src="https://user-images.githubusercontent.com/194400/68499996-8169f480-0252-11ea-9f72-97d657b81eb2.png">

# 💸 

Now to wait 6 - 8 weeks for it to arrive ... 🚢 ⏳ 

@iteles did Samir confirm that he had _placed_ the order? 💭

**Comment by iteles** [comment]
@nelsonic Nope. They said they'd call but didn't.

**Comment by nelsonic** [comment]
@iteles want to call them now? (_they don't work weekends..._)

**Comment by iteles** [comment]
I've been trying but they're not picking up :/

**Comment by nelsonic** [comment]
@iteles by now they are half way around the world with our cash ... 🙄

**Comment by iteles** [comment]
OK, they called me back. Apparently they got the email and are processing the order but of course it's not the weekend already in China. He said he'd call back on Monday with more concrete timelines.

**Comment by iteles** [comment]
Spoke to Bruna today and the transporter is delayed and not expected in Leixões until 12th February 🤦🏻‍♀️🤦🏻‍♀️🤦🏻‍♀️

**Comment by nelsonic** [comment]
Cool. I don't need furniture to start living in the house. 👍
I slept a whole summer on the floor on an air mattress, without a wardrobe or anywhere to store my things, living out of a suitcase and it was _great!_ 🚀

**Comment by iteles** [comment]
👍 Same

**Comment by iteles** [comment]
Confirmed today that the expectation is that the container will arrive on 13-Feb-2020 and that the transport to Braga will be the next day.

I have asked Samir to also look into getting the 'empilhadora' necessary to lower the machine from the truck to ground level. He mentioned it would be about €50 an hour, only 1 hour should be necessary and will confirm with us nearer the time.

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/76163779-11587600-6141-11ea-93d1-18bfadc876e1.png)

**Comment by nelsonic** [comment]
Image without text:
![image](https://user-images.githubusercontent.com/194400/76163822-6dbb9580-6141-11ea-8115-10dfb8086acd.png)

**Comment by nelsonic** [comment]
Air Quotes image without text:
![image](https://user-images.githubusercontent.com/194400/76164020-28986300-6143-11ea-8c4f-d8e1bae3eb16.png)

**Comment by nelsonic** [comment]
In 2019 pre-pandemic supply chain constraints and "chip shortages" ..., 
the 1300x2500mm 130w laser cutting machine cost **`€7,499`** + VAT (IVA) which I though was a _good_ deal! 
see: https://github.com/nelsonic/nelsonic.github.io/issues/455#issuecomment-549803532 above (this is why we take screenshots!)

In 2022 the _exact_ same machine from the same seller costs  **`€14,600`** ... **almost _double_**!
https://3doutlet.shop/product/maquina-de-corte-gravacao-a-laser-1300x2500mm-130w/

![image](https://user-images.githubusercontent.com/194400/148615464-a839ee36-014e-47f7-9536-7e3258d8cd3a.png)

We could sell our machine for more than we paid for it ... 💰 
How many Hedge Funds have doubled their money in the last 2 years? 🤣 

Obvs not selling our machine. Just went looking for something on their site and saw this and was amused.

**Comment by nelsonic** [comment]
@hyprstack this is the laser cutter we got: https://github.com/nelsonic/nelsonic.github.io/issues/455#issuecomment-549803532 in 2019. ⚡ 
It's total overkill for "Hobby" projects. 🙄 
But I want to build actual [furniture](https://github.com/dwyl/home/tree/master/furniture) with it so I figured having a "full-size" bed was the way to go.

And as you can see from the thread https://github.com/nelsonic/nelsonic.github.io/issues/455#issuecomment-1007791620 it's gone up in price in the 2 years we've had it so it's basically an "investment" that's been sitting appreciating in value. 📈 😜
As soon as I'm finished with my current coding contract I'm planning to spend 2 days a week doing CAD/CAM + Furniture making. 

When you visit us in Braga I will show you how it works (if you don't already know...).
