### ISSUE TITLE
Startup School 2018

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/nelsonic.github.io#511]
https://blog.ycombinator.com/startup-school-2018-curriculum
via/comments: https://news.ycombinator.com/item?id=17708469

@iteles what do you think about _applying_ for this? 
(_as a catalyst to build the @dwyl app/product...?_)

**Comment by iteles** [comment]
This was a bit of a black hole of links 😄 

I _Love_ this idea, either way we should follow along with the lessons.

We have quite a lot on in September, shall we catalog it together and make sure there is time to show progress to a mentor in order to use the help as much as possible on a week by week basis?

In the meantime, we should fill in the application anyway, it will be great for clarifying 'the pitch' 😉  Win-win

**Comment by nelsonic** [comment]
@iteles stoked you found the time to take a look and do some link-crawling. 🎉 
When do you have time to sit down with the application form? (_e.g: tomorrow morning 08:00...?_)

**Comment by iteles** [comment]
If you prefer the morning (which I know you do), Friday would be preferable. I have 🦆s to get in a row.

**Comment by nelsonic** [comment]
@iteles I just want to "divvy up" the tasks for the application ASAP in case I need to work on a "demo" or defining something that is going to take time ...

**Comment by nelsonic** [comment]
[![image](https://user-images.githubusercontent.com/194400/44621133-0f053280-a8a1-11e8-8066-0c3f9b1f2c00.png)](https://youtu.be/BTS-rFzROOg)
https://youtu.be/BTS-rFzROOg

**Comment by iteles** [comment]
I also filled in the first page 👍

**Comment by nelsonic** [comment]
This is a _useful_ list of all YC companies: https://yclist.com
It's _insightful_ to see how many are "dead" or "exited".
![image](https://user-images.githubusercontent.com/194400/43990322-94ec7e4e-9d52-11e8-9081-fe9d50b060eb.png)

I would be _especially_ interested in doing a "meta analysis" 
to understand why companies succeed/fail.
(_fairly certain YC have this data/insight as their "secret sauce"_)

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/43990470-fa7c763c-9d53-11e8-9cd4-44763b476f9a.png)

![image](https://user-images.githubusercontent.com/194400/43990477-07819d8a-9d54-11e8-82fe-bcab1b06c07f.png)

Devtools Console open:
![image](https://user-images.githubusercontent.com/194400/43990505-472196ca-9d54-11e8-8445-b23f589cd416.png)

+ [x] Company Name
+ [x] Company URL
+ [x] Describe your company in a sentence or two. `<input maxlength="60">`
+ [x] Vertical:
```html
<select class="select required" name="company[vertical_id]" id="company_vertical_id">
<option value=""></option>
--
  | <option value="1">Agriculture / Agtech</option>
  | <option value="2">Artificial Intelligence</option>
  | <option value="3">Augmented Reality</option>
  | <option value="4">B2B</option>
  | <option value="5">Biomedical</option>
  | <option value="6">Biotech</option>
  | <option value="7">Community</option>
  | <option value="8">Consumer</option>
  | <option value="9">Crowdfunding</option>
  | <option value="10">Developer Tools</option>
  | <option value="11">Diversity</option>
  | <option value="12">Drones</option>
  | <option value="13">E-commerce</option>
  | <option value="14">Education</option>
  | <option value="15">Energy</option>
  | <option value="16">Enterprise</option>
  | <option value="17">Entertainment</option>
  | <option value="35">Esports / Online Gaming</option>
  | <option value="18">Financial / Banking</option>
  | <option value="19">Government</option>
  | <option value="20">Hardware</option>
  | <option value="21">Healthcare</option>
  | <option value="22">International Market</option>
  | <option value="23">Jobs</option>
  | <option value="24">Marketplace</option>
  | <option value="25">Media / Advertising</option>
  | <option value="26">Moonshots / Hard Tech</option>
  | <option value="27">Nonprofit</option>
  | <option value="33">Other</option>
  | <option value="28">Robotics</option>
  | <option value="29">Science</option>
  | <option value="30">Security</option>
  | <option value="34">Sport / Fitness</option>
  | <option value="31">Transportation</option>
  | <option value="36">Travel</option>
  | <option value="32">Virtual Reality</option>
</select>
```
+ [x] What is your company going to make? `<textarea maxlength="200">`
+ [x] Why did you pick this to work on? `<textarea maxlength="250">`
+ [x] Are you currently part-time or full-time on this startup? 
```html
<select class="select required" name="company[commitment]" id="company_commitment">
<option value=""></option>
--
  | <option value="full_time">Full Time (40+ hours a week)</option>
  | <option value="part_time">Part Time (20+ hours a week)</option>
  | <option value="other_commitment">Other</option></select>
```
+ [x] Which of the following best describes your progress?
```html
<select class="select required" name="company[stage]" id="company_stage">
<option value=""></option>
--
  | <option value="nothing">Nothing Built</option>
  | <option value="idea">Idea/sketches</option>
  | <option value="mocks">Mocks/Renderings</option>
  | <option value="prototype">Prototype/pre-launch</option>
  | <option value="private_beta">Private Beta</option>
  | <option value="public_beta">Public Beta</option>
  | <option value="preorders">Taking Preorders</option>
  | <option value="launched">Launched</option></select>
```
+ [x] How far along are you? `<textarea maxlength="250">`
+ [x] Have you incorporated your company?* [yes/no]

**Comment by nelsonic** [comment]
Female founders: http://www.ycombinator.com/companies/?has_ff=true
![yc-female-founders](https://user-images.githubusercontent.com/194400/43990862-7fcca316-9d59-11e8-96be-12e4e20f73df.png)

https://blog.ycombinator.com/yc-winter-2018-stats/
![yc-w18-female](https://user-images.githubusercontent.com/194400/43990851-632abc84-9d59-11e8-956a-73d464af52c1.png)

**Comment by nelsonic** [comment]
@iteles recommended reading: "Requests for Startups" https://www.ycombinator.com/rfs/

**Comment by nelsonic** [comment]
http://www.femalefounderstories.com

**Comment by nelsonic** [comment]
Michael Seibel (YC CEO) office hours:https://youtu.be/JJ2BWOT4hfs
27:42 MS: “when I think about doing the pitch, these are the things that actually stand out to me: 
1: clarity and conciseness, _more words_ are actually _bad_. When you feel like you are pitching for a long period of time, that’s a bad sign typically.

**Comment by nelsonic** [comment]
@iteles thinking of including a link to the "Feedback App" in YC SS App
(_as it's our only **relevant** "live" MVP..._)
please see: https://github.com/dwyl/feedback/pull/95#issuecomment-412493700

**Comment by iteles** [comment]
@nelsonic Reviewed, thanks.
Also, see https://github.com/dwyl/code-of-conduct/pull/6

**Comment by nelsonic** [comment]
@iteles I have prepared a ***`draft`*** of the answers for the Startup School Application.
please see: https://github.com/nelsonic/home

I am working on adding context and supporting evidence below the **`tl;dr`** so that when YC partners read the "web page" they will be _convinced_ to give you/us a spot!

My goal for the rest of today is to:
+ [x] finish writing the Markdown
+ [x] transform the markdown into AMP-compliant HTML using https://github.com/dwyl/ampl
+ [x] Add a "Landing Page" _Theme_ to the HTML so it _looks_ "_presentable_".
+ [x] Ship the Page on: https://dwyl.com/home (without the existing layout/navigation etc)

Please let me know your thoughts on this and if you have time for a "call" just call me!
Thanks!

**Comment by iteles** [comment]
:sob: I don't want to take the wind out of your ⛵️ but I've just seen this, looks like they closed the applications early 😞😞  

https://www.startupschool.org/
<img width="654" alt="screen shot 2018-08-13 at 16 24 57" src="https://user-images.githubusercontent.com/4185328/44041387-947a9832-9f15-11e8-8af8-61829cd85c44.png">

I hereby commit to 'auditing the course' and _making_ time for this every week _anyway_.

**Comment by nelsonic** [comment]
I still see:
![image](https://user-images.githubusercontent.com/194400/44043131-fbfc0ece-9f19-11e8-98ea-b012b9c369bb.png)

Going to add it.

**Comment by nelsonic** [comment]
@iteles just tried to call you but got "GiffGaff Voicemail" ... 😞

**Comment by nelsonic** [comment]
@iteles I think you were seeing the "NO" page because you weren't _logged in_ ... 😕 

I logged in ("as you"):
![image](https://user-images.githubusercontent.com/194400/44043648-482bb33e-9f1b-11e8-8440-720b9cdcb0b3.png)

![image](https://user-images.githubusercontent.com/194400/44043356-967ef5ba-9f1a-11e8-832d-999e86eef0e5.png)
![image](https://user-images.githubusercontent.com/194400/44043467-d634570e-9f1a-11e8-9f0c-7ef67a98292a.png)
![image](https://user-images.githubusercontent.com/194400/44043480-e000b2fa-9f1a-11e8-97b2-8617a0a6f549.png)
![image](https://user-images.githubusercontent.com/194400/44043524-fd6c9b56-9f1a-11e8-9f75-20a811676d34.png)

Your company is _there_:
![image](https://user-images.githubusercontent.com/194400/44043677-56a158b0-9f1b-11e8-9859-4d91549a4f09.png)

You can edit it to your heart's content. 📝 

And I didn't even have to resort to LinkedIn Messaging Michael... 😉 
I was _prepared_ to ... https://www.linkedin.com/in/mwseibel 
This is not an opportunity we want to _miss_. 

Anyway, back to my plan.
Will send you a PR with the page for dwyl.com before midnight.

**Comment by iteles** [comment]
@nelsonic :tada: 🙏 : !

Thanks for submitting.
<img width="1157" alt="screen shot 2018-08-13 at 17 13 07" src="https://user-images.githubusercontent.com/4185328/44044124-87a33edc-9f1c-11e8-9381-0f7abf903700.png">

**Comment by nelsonic** [comment]
@iteles thanks for invite:
![image](https://user-images.githubusercontent.com/194400/44044199-c59e5276-9f1c-11e8-91bf-d86090b326b0.png)

But I'm _super busy_ with building someone `else`'s website ...

**Comment by nelsonic** [comment]
Totes McJoking ... **invite _accepted_**.
![startup-school-invite-accepted](https://user-images.githubusercontent.com/194400/44044474-94df7402-9f1d-11e8-807c-c77670d0c5d3.png)

Which means _(y)our_ Startup School Application is now **complete***. ❤️ ✅ 🏡 

Now, we _blitz_ it to get the landing page up. https://dwyl.com/home (_currently `404`..._)
![dwyl-home-404](https://user-images.githubusercontent.com/194400/44044554-d4177822-9f1d-11e8-81f1-bf0cec07c5bf.png)

**Comment by nelsonic** [comment]
Startup Playbook: http://playbook.samaltman.com

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/44236102-c3b59a80-a1a3-11e8-961d-4563e942bbcf.png)

@iteles when you can: https://github.com/dwyl/dwyl-site/pull/462
Thanks!

**Comment by iteles** [comment]
<img width="1110" alt="screen shot 2018-08-16 at 23 12 07" src="https://user-images.githubusercontent.com/4185328/44237864-2316a900-a1aa-11e8-8ae7-335db7b474a5.png">

Deployed, but something's not quite right.

**Comment by nelsonic** [comment]
Are you able to debug it?
If not, I can take a look in the morning...

**Comment by nelsonic** [comment]
Moore’s Law of Real Estate (2012!): 
https://youtu.be/JQ6irnso40c

**Comment by iteles** [comment]
I was already in bed by the time you wrote that last night and at a bus stop right now so won’t be able to use my computer for a little while yet 😬

**Comment by nelsonic** [comment]
Totes working https://dwyl.com/home ✅ 
![image](https://user-images.githubusercontent.com/194400/44293352-414fd800-a282-11e8-823c-348defe201b2.png)

**Comment by iteles** [comment]
This is what "_rejection_" looks like: 😞 
![image](https://user-images.githubusercontent.com/4185328/44421149-0d292f80-a580-11e8-93f6-b9d276257135.png)


And this is what it looks like when they realise that "_the software_" made a "mistake":
![image](https://user-images.githubusercontent.com/4185328/44421218-334ecf80-a580-11e8-8f9a-5304a9ff8e57.png)
![image](https://user-images.githubusercontent.com/4185328/44421241-406bbe80-a580-11e8-9bf4-96656fdb1628.png)

# `#accepted` :wink:
https://youtu.be/SsoOG6ZeyUI

**Comment by nelsonic** [comment]
@iteles I _knew_ you would get in! 🎉 

what's _next_...? 
Do you want to take a couple of hours this evening or tomorrow to go through the "curriculum"?

**Comment by iteles** [comment]
I didn't, you did, but yay! Thanks for writing and submitting the application.

Yes, we'll need to spend time over the weekend to fill out our profile and go through the time commitments over the next few weeks. Whenever you have time.

**Comment by nelsonic** [comment]
To _clarify_ for posterity: I _wrote_ the YC SS application on your/our behalf based on _many_ verbal conversations we've had _because_ you did not have time to focus on it. 
you were scheduled to spend time with your family for the weekend preceding the deadline 
and the little "spare time" you had was spent on catching up on @dwyl work 
so that you could spend quality time with your Grandma, brother, cousins and aunts/uncles/parents. 
I _chose_ to "***exclude***" **myself** from the family weekend
***so that*** I could put the application into writing: https://github.com/dwyl/home 
and **`<input type="submit" value="Accelerate">`** our learning as part of building the Braga **`home`**.

I think that _long-term_, _diligently_ following the Startup School curriculum 
will be one of the _best_ time investments we will make in our _lives_.
Yes, it's going to require a _lot_ of work considering there is still _lots_ of "@dwyl London" work to do
and there is both (a ton of) carpentry and "interior finishing" work that we need to get done in the house ***`before`*** we can open to the **`public`** ... but I'm _excited_ to get it all done!

# If You Want Something _Done_, <br /> Ask a _Busy_ Person To Do It ~ [Anonymous](https://quoteinvestigator.com/2018/01/30/busy)

**Comment by nelsonic** [comment]
Jessica Livingston Founders at Work Google Talk: https://youtu.be/z6hoPw5hItY
The book is _obviously_ a “Must Read” for founders, but in this video presentation, JL actually gives a good summary.

**Comment by nelsonic** [comment]
Jessica Livingston - What's Different about "Unicorns"
[![image](https://user-images.githubusercontent.com/194400/44643214-03fcf000-a9d0-11e8-9e6c-1550904a40e7.png)](https://www.youtube.com/watch?v=Ygr3rx4hSsc&list=PLQ-uHSnFig5OfUA6Kgif-AfRFJhkFksXI)
https://www.youtube.com/watch?v=Ygr3rx4hSsc&list=PLQ-uHSnFig5OfUA6Kgif-AfRFJhkFksXI
(female founders conference playlist)

It _boggles_ my mind how 16% of people "down-voted" the video ... it's a _superb_ talk with lots of actionable insight and advice for female founders!

The corresponding Blog Post: http://foundersatwork.posthaven.com/whats-different-about-unicorns
is a great summary if you need a quick recap.

**Comment by nelsonic** [comment]
@iteles let's put some time into _revisiting_ and _capturing_ our "Mission" (statement) today.
e.g: https://www.tesla.com/about
![image](https://user-images.githubusercontent.com/194400/44710625-d3d74f00-aaac-11e8-8768-8064a6b91d8e.png)

The mission was _recently_ changed from "**sustainable _transport_**" to "**sustainable _energy_**":
https://futurism.com/tesla-changes-one-word-in-its-mission-statement-and-it-already-says-a-lot/
![image](https://user-images.githubusercontent.com/194400/44710574-b4d8bd00-aaac-11e8-8ee9-2cca9d33155f.png)

Telsa ("Super Secret") "Master Plan":
https://www.tesla.com/blog/secret-tesla-motors-master-plan-just-between-you-and-me

**Comment by nelsonic** [comment]
https://youtu.be/ZoqgAy3h4OM

**Comment by nelsonic** [comment]
I tried to build enthusiasm for this project and following "Startup School" ...
the https://github.com/dwyl/home/graphs/contributors tells you _all_ you need to know about this:
![image](https://user-images.githubusercontent.com/194400/48839510-a46e7080-ed83-11e8-830e-1e8ccebeabb5.png)

One person putting in _hundreds_ of hours of research.
The other getting distracted by busywork and watching TV.
