### ISSUE TITLE
Elm 0.19 Broke Us 💔

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/nelsonic.github.io#516]
https://dev.to/kspeakman/elm-019-broke-us--khn

**Comment by rub1e** [comment]
I clicked this by accident but I was curious so I read the first (non-technical) part of the article

What are your thoughts re the need for an engaged and super-positive community (and the impact of not having this) for new technologies like this to succeed?

**Comment by nelsonic** [comment]
A welcoming community is the difference between success and failure.  
Evan's recent talk "What is Success?” is _really_ worth watching: https://youtu.be/uGlzRt-FYto

Kasey Speakman (the author of the "Elm 0.19 Broke Us") has *some* "justification" for being "heart-broken" about Elm "breaking" his love of the language/platform because the changes have "*affected*" him (and his team) _personally_ and he has *some* grain of truth with regards to Evan being a "BDFL" who closes issues *swiftly* (_often unceremoniously_) but a _fact_ that is _not_ captured in this blog post is that building an Open Source package or (_in the case of Elm_) _entire ecosystem_ is like building a _City_. Essentially Evan has "pedestrianised" one of the main roads in the centre of the city to make it more "walkable" but it means people who are used to "driving through" can no longer do it.
This will make _existing_ "users" _angry_ but it's an "investment in the long term". 
The _reason_ I mention City-building is because it's large and complex and changing things affects _many_ people. And the city-planner is a busy person who needs to make _difficult_ decisions.

Indeed the comments thread on HN balances out the "one-sidedness" of this post.
see: https://news.ycombinator.com/item?id=17842400

Evan works for **`No Red Ink`** which is _by far_ the biggest user of Elm. 
Everyone at **`No Red Ink`** got a chance to review/test Elm `0.19` pre-release and if they felt that it was a "bad idea" they would have informed Evan. 
The most recent Elm Town Episode: https://elmtown.audio/upgrading-to-elm-019-luke-westby-richard-feldman features Luke Westby & Richard Feldman (both of **`No Red Ink`**) and they discuss the 0.19 release in more detail than the blog post. 

Ultimately I feel that 0.19 is a _good_ release that benefits both end-users of any Apps built with Elm (because compilation is faster and resulting apps smaller) and beginners have less to get confused by; custom operators are a "nice to have" but they make code "terse" and difficult to debug.

Interestingly, **`Elixir`** (_our other programming language_) of choice @dwyl is going in the _opposite_ direction to Elm in that it _seldom_ removes features from the language and has an _incredibly_ powerful "meta programming" language (macros) built-in which allows users to _extend_ the language to their heart's content. 

I _feel_ the pain of people who have "lost" a language feature they used/loved but I think it's _better_ for the overall ecosystem and _specifically_ for beginners joining an Elm project. 
I'm still "_bullish_" on Elm and will continue using it for the foreseeable future. 
Elm is "Touring Complete" and has _all_ the features we need to build full applications that are fast, reliable and easy to maintain. 
I actually _love_ the fact that Evan is "pruning" features that are "stumbling blocks",
I think the language should be as minimal as possible much like the _original_ lego.
And if people do not have the _imagination_ to build using the "basic" blocks, they should "graduate" to using the more advanced PureScript/Haskel or ClojureScript so they can have all their "advanced" features. 
People _easily_ forget (_or don't think about in the first place_) that the _original_ Google Mail (GMail), Google Docs and Google Maps were all built using ECMAScript 3! and it did not "stop" them from building "advanced" applications with good UI. 

If the engineers at Google could build/ship _entire_/_advanced_ web applications with ES3 which did not have built-in type-checking, advanced compilation and time-travelling debugging, then people whining about Elm 0.19 need to re-think how they are _over-complicating_ their own lives!

![image](https://user-images.githubusercontent.com/194400/45017391-6765ce00-b01f-11e8-9ee4-2ddfdf884554.png)

**Comment by rub1e** [comment]
V v interesting - will have to read this properly and check out some of the links!

**Comment by nelsonic** [comment]
GOTO: https://github.com/dwyl/learn-elm/issues/129#issuecomment-2337560741
