### ISSUE TITLE
Going to Doctors Tomorrow

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/nelsonic.github.io#662]
I have been suffering from ***moderate***<sup>1</sup> and persistent abdominal pain for a **`while`**.
I keep hoping that it will "_go away_" but does not appear to be subsiding.
So going to the Doctor tomorrow to get it checked.

# Please DON'T READ Below This Line  🙏 `#Personal`

<hr />

The area that hurts corresponds to the **large intestine** or "***descending colon***".
![image](https://user-images.githubusercontent.com/194400/52363166-044aee00-2a3a-11e9-945c-6a3bd20db077.png)
According to my research https://www.webmd.com/digestive-disorders/picture-of-the-abdomen#1
There are a _number_ of "conditions" my pain is symptomatic of.
So I don't want to jump to any conclusions or "self diagnoses" which will _inevitably_ be incorrect.
I just want to see the doctor and find out if there is any "scan" or "test" that can be done.

The _effect_ of the pain often "***unignorable***" (_that's a [real word](https://www.merriam-webster.com/dictionary/unignorable), I checked_). 
These last few days I've been taking afternoon naps not only because I'm _exhausted_,
but also to _escape_ the pain; it's _really_ unpleasant.
Even when I sleep I don't feel "rested"; I feel _weak_. 
Which makes it _very_ difficult to _concentrate_ on the work I have to get done. 😞 

Historically, I do not "_cope_" very well with "travelling".
My body "shuts down" and I am unable to use the bathroom for _days_.
The lack of staying in "one place" or having a good (_healthy_) food routine is also taking it's toll.
I sometimes go for _days_ without "_effective elimination_" and I feel like I have a "build up" 
that I would _medically_ describe as "**constipation**" verging on an "**intestinal _obstruction_**". 

# I _asked_ you _not_ to read this ... 🙄 

My [**food poisoning**](#613) at Christmas was a **_temporary_ relief**.
It felt _horrible_ at the time when I could not keep anything "down", but the "emptiness" was _great_!
For a _few_ days I was _without_ pain, but it gradually returned and I ***lost*** my "**_regular_ movement**". 

Being with my _consistently_ over-eating (_obese_) family, and having to _conform_ culturally 
with an "evening meal" even when I _know_ it will not _help_ me and I don't _need_ to eat,
is _especially_ infuriating. People simply don't (_want to_) _understand_ that "3 meals a day" is a _super_ recent phenomena in human evolution/history ... our ancestors didn't _use_ to (_over_) eat this way! Our Palaeolithic ancestors used to ***fast*** (_not by choice, but due to food scarcity_) which allowed their bodies to _rest_ between meals. Food conservation/storage is a relatively _recent_ development. 

The _second_ half of January has been _particularly_ painful. 
Starting with the Morocco trip where I only ("_successfully_") used the toilet for one night 
(_the night when I skipped dinner and had to **apologise** for my **absence** ... 
like missing a meal is somehow a **crime** or an "**insult**" to the **multi-day** "**birthday girl**"...!
but I digress ... the point is Morocco was **really bad** for me in more ways than one._)

_One_ of the things on my list from IKEA is/was a "bathroom stool".
With the _hope_ of using it as a "squatty potty" for more "_effective elimination_" ... (_["**TMI**"](https://www.google.com/search?q=too+much+information+meme&tbm=isch), I know_!)
I've put _off_ going to IKEA in the _hope_ that the basement windows would be finished
and I can ***finally*** use the [Maslow CNC](https://github.com/nelsonic/learn-cad-cam-cnc/issues/71) to make my _own_: https://github.com/nelsonic/bathroom-stool/issues/1

I think the fluctuation in my **abdominal** (_both sub cutaneous and visceral_) **fat** is the _cause_ of the pain.
But it's a _localised_ highly specific area and does not "shift" at all from day to day. 
The acuteness of the pain does oscillate depending on a number of things,
So far the only thing that I've found to alleviate the pain is _sleep_. 
Sitting at a desk is the _worst_ as it compresses the area and aggravates the pain.
I _know_ the **Doctor** will tell me "_lose weight_" ... 
Doctors give _every_ "_overweight_" person that advice. 
No ["system"](#650) just (_go away and_) do it.

Last year I managed to burn off **18kg** of fat through super-human discipline and effort.
The chap from the DEXA scan said I was in the 99th percentile of fat loss for 3 months,
and I should "keep it up" ...

As you know, last June "one thing lead to another" and I lost "_focus_" 
(_or "**motivation**" or whatever you want to call it ..._)
I also _completely_ lost my _routine_ and was subjected to **constant** ***visible*** "***junk***" in **Gerês**.

When a person who has _historically_ used "emotional eating" as a "coping mechanism",
has an emotional "blow", and that "down" coincides with the ***visibility*** of **junk**,
the person has a **_high_ propensity** to want to _consume_ the **junk** to "_comfort_" themself. 

There's no _point_ me attributing "_blame_" to whoever left unhealthy food on the _counter_ in Gerês,
or "_pointing fingers_" at anyone else for late night meals of the _wrong_ things. 
It's nobody's "_fault_" but my own. I am _responsible_ for the food or "_junk_" that enters my body. 

_However_ when I am _tired_ and _depressed_, my willpower _plummets_ 
and my "_defences_" against sugar, carbs, processed food _evaporates_.
If I'm still awake at 22:00 and feel _exhausted_ and _sad_, and the junk is _available_
I can take down 3 burgers in a single _breath_ without even _thinking_.
I will _hate_ myself for it in the _morning_. 
But as _anyone_ who has studied _basic_ human psychology knows,
"hating" oneself for something self-inflicted only _exacerbates_ the problem. 
If _eating_ is your "fix" and you feel bad for eating (_the "wrong" things_),
the problem is **_rapidly_ compounded** and the **18kg** of **hard _lost_ fat** is resumed. 😞 

I have tried my _best_ to be "_good_" since I got the new body mass scales in early December,
but the _constant_ exposure to sugary/proceed foods and exhaustion has _often_ got the better of me.
I have _succeeded_ in maintaining my ["**exercise _streak_**"](https://github.com/nelsonic/nelsonic.github.io/issues/621#issuecomment-461141179) ... 
I did pushups and squats when I had _food poisoning_ to not "_lose_" the streak ...
But as we all know ...

![you-cannot-outrun-your-fork](https://user-images.githubusercontent.com/194400/52365891-63136600-2a40-11e9-9a49-92fca8d1265e.jpg)

Not saying that doing exercise is _pointless_ but even 30 mins of _vigorous_ exercise, 
(_which is the baseline I have maintained for the last [**137 days**](https://github.com/nelsonic/nelsonic.github.io/issues/621#issuecomment-461141179), amongst other streaks before then!_)
is _erased_ by a single piece of toast with butter & jam. 
And eating at the "_wrong_" time of day (_which is **always** the case with **family**_)
compounds the effect because eating too late in the day means glycogen stores are over-filled
and ***de novo lipogenesis*** kicks in, i.e. eating late **_creates_ fat**.
https://paleoleap.com/science-turning-carbs-to-fat-de-novo-lipogenesis/
I've _known_ this for a **`while`** and it's the _reason_ I wrote about want to "_skip_" dinner in: [`goals.md`](https://github.com/nelsonic/nelsonic.github.io/blob/3fe7ef8a196c1d3355c41d5a40940c584343cdd8/draft/goals.md)
![image](https://user-images.githubusercontent.com/194400/52366941-d0c09180-2a42-11e9-8f1e-158fb8428644.png)

It's my own _fault_ for not ***publishing*** and _sharing_ my goals with people.
Let's _fix_ that ***now***! https://github.com/nelsonic/nelsonic.github.io/commit/cee5a8d612c453fe42c20d3adfd26c6a7b2b3940
[https://github.com/nelsonic/nelsonic.github.io/blob/master/**public**/goals.md](https://github.com/nelsonic/nelsonic.github.io/blob/master/public/goals.md)

> <sup>1</sup>While searching for the appropriate pain threshold word (_official medical scale_) 
(_e.g: mild, moderate, acute, sever_), I learned a **`new`** word today: "***catastrophizing***". 🙄 
which is: "_view or present a situation as considerably worse than it actually is._"
see: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5043012/
Catastrophizing is similar to [hypochondria](https://en.wikipedia.org/wiki/Hypochondriasis), people tend to over-estimate the severity of _everything_. 
https://www.psychologytoday.com/us/blog/friendship-20/201611/5-ways-stop-catastrophizing

**Comment by iteles** [comment]
Let me know what time you would like to leave please and I'll go into town with you 👍

**Comment by nelsonic** [comment]
@iteles considering going to [Clínica Santa Tecla](http://clinicasantatecla.pt/) after morning standup.  i.e. **09:50** 🚗 

But I'm _also_ aware that the later I leave it the longer the _wait_ will be ... ⏳ 
So I could be tempted to go _first_ thing in the morning to avoid the queue ... 🙄 
Annoyingly, their website does not list their opening hours ... 😕 
But Google is more helpful: 🔍 
![image](https://user-images.githubusercontent.com/194400/52371288-ffdc0080-2a4c-11e9-92b0-df63259c2265.png)

You _definitely_ don't have to go; it's a _waste_ of your time. ⏳🔥

**Comment by iteles** [comment]
I called, they recommend being there at 08h45 to fill out the forms before the day shift doctors arrive at 09h00 :+1:
Took me 30 minutes to get to the house yesterday with mid-afternoon (14h30) traffic.

**Comment by nelsonic** [comment]
Leaving Tadim at **08:20** then. 🌅

**Comment by iteles** [comment]
:+1: I need to go into town for to go to the town council so I would appreciate coming along 😊

**Comment by nelsonic** [comment]
@iteles linking to issues watched by _many_ people is a good way to _publicise_ my doctors trip ... 🙄 
sure. sounds good. 👍

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/52376897-3882d680-2a5b-11e9-86d0-2eca9b219055.png)

I guess it's my own "_fault_" for posting this issue.
I'm not bothered. Google _knows_.

**Comment by iteles** [comment]
Entirely my bad. :-1:

**Comment by nelsonic** [comment]
@iteles the reference in the other issue does not _dissappear_ simply because you updated the comment ...
![image](https://user-images.githubusercontent.com/194400/52415107-0c5c6980-2ade-11e9-9966-19a30118e51a.png)
Just be more _mindful_ in future ... 
Again, I'm not "upset".
Google knows _everything_.
