### ISSUE TITLE
ALC?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/nelsonic.github.io#7]
# ALC > Awesome Learning Community<sup>1</sup>

Awesome Learning Community (ALC) helps everyone track and share everything they learn!
## Why?

@**dwyl** we **_love learning**_!  
**_Most**_ of the **_people**_ we know also **_love learning new things**_!
(_we don't hang out with people who already know everything..._)  
We are _frustrated_ that we don't have a way of
tracking all the things we have learned
and _don't have_ **_instant access**_ to an "archive" of all our knowledge...  
Sure, we can "Google" for things to refresh our memory when we
forget something. But what happens when you don't have Google...?!
(_shock-horror! you could be offline...!_)

Wouldn't it be **_awesome**_ if there was a **_complete list**_ of **_everything you ever learned**_ from day one of your life...?
What if all the things you know were instantly searchable (_with auto-completion & typo-correction_) and **_easily shareable**_ with
anyone (_or kept_ **_private**_ _from marketers trying to sell you stuff_!) and you had a "**_to-learn**_" **list** with
everything you want to learn for a **_specific goal**_ in life...?
## _Potential_ Features

![awesome-learning-community-wiki-learn-list](https://cloud.githubusercontent.com/assets/194400/7604270/b08ffe04-f937-11e4-9a35-8b72b4c130f7.jpg)

Jotted down a few "requirements" last year... 
none of them are "original" thoughts.
I credit [Owen White](https://www.linkedin.com/profile/view?id=9316117) for hiring me to work on his "Progress 360" project while at Pearson.
These are _general_ features of a collaborative learning platform.
Sadly the product @tonydaly and I built while we were @Pearson was mothballed when Owen left (in the great re-org of 2014...) which is why I **_never**_ want to work on _anything_ **_closed-source again**_!!
"Progress 360" which became the "**_tilr**_" **MVP** had a _couple_ of these features, namely people could post short updates on what they had learned and those were viewable by their friends. But the funding for Owen's project was cut and thus thus 99% of the features we _hoped_ to build were never written.

I want to build an open source learning platform anyone can extend!

<sup>1</sup> ALC is a _working title_.
I'm _sure_ someone will come up with a better name for this!

**Comment by nelsonic** [comment]
This is now at: https://github.com/dwyl/alc

**Comment by tonydaly** [comment]
@nelsonic this is awesome

**Comment by nelsonic** [comment]
@tonydaly you up for a week in Portugal this summer to pair on a few features...?
The Flat is 5mins from beach. Free food & Fibre Internet. 
![beach](http://fc07.deviantart.net/fs71/f/2012/122/0/a/sunset_at_carcavelos_beach_by_ailda-d4yaay8.png)
If interested, let us know! we would _love_ to have your genius input! :wink:
