### ISSUE TITLE
Generation Alpha

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/nelsonic.github.io#810]
https://en.wikipedia.org/wiki/Generation_Alpha

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/89732019-a5f23780-da43-11ea-847f-0fd921e6b0b6.png)

**Comment by iteles** [comment]
This is a good second name but not a great first name in my opinion. If a kid is a bit scrawny or less confident, it’s opening them up to all kinds of extra bullying.

**Comment by nelsonic** [comment]
There's _Zero_ chance of a kid practicing swimming and karate from age 2, 
having good nutrition, plenty of sleep and being coached on posture being "_scrawny_"!

![alpha-vs-beta-posture](https://user-images.githubusercontent.com/194400/89743074-70773980-da97-11ea-9bb4-7cf52f4a517b.png)

Also, "Alpha" can mean a lot of different (_positive_) things not just _physical_ prowess.

+ Alpha is the first letter in the Greek alphabet: https://www.vocabulary.com/dictionary/alpha
+ Physics: alpha particles: https://en.wikipedia.org/wiki/Alpha_particle | alpha radiation: https://en.wikipedia.org/wiki/Alpha_decay
+ Software: early testing stage of a software or hardware product; “alpha version”
+ Investing: https://www.investopedia.com/terms/a/alpha.asp 
+ Photography/Creativity: https://youtu.be/5kDlZVgrFmA |> https://youtu.be/2xKSOrHm8Zs |> https://www.instagram.com/sonyalpha I defy anyone to suggest that Photos/Video cannot be produced by people who might be labeled "scrawny". _Anyone_ can `#BeAlpha`

The surprising science of alpha males: https://youtu.be/BPsSKKL8N0s
[![image](https://user-images.githubusercontent.com/194400/89740171-63018580-da7e-11ea-94cf-a694d162bbdc.png)](https://youtu.be/BPsSKKL8N0s)



These people appear to have done "OK": https://en.wikipedia.org/wiki/Alpha_(name) (_it's a **gender neutral** name_)
But most didn't live in the era of wokeness where once perfectly acceptable words are now deemed _negative_. 🤦

**Comment by nelsonic** [comment]
Closing as "informative" but not "_actionable_". ✅
