### ISSUE TITLE
Silent Computer Mouse

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/nelsonic.github.io#825]
Last year when I was on the hunt for a **quiet** and reasonably priced computer mouse,
I bought a **Logitech M330 Silent Plus** from Amazon UK and it worked well, the buttons are **_virtually_ silent**.
https://www.amazon.co.uk/gp/product/B01K7GEAFC

![image](https://user-images.githubusercontent.com/194400/100112791-8d2d5680-2e67-11eb-8bd6-7330233b1769.png)

![image](https://user-images.githubusercontent.com/194400/100112897-a9c98e80-2e67-11eb-97ee-c90334d66d1a.png)

Apparently, we paid **£25** for it last year and now it's _considerably_ cheaper for some reason.
I think it's _good_ value even at £25. So at **£10.57** it's a **_bargain_**.

When my parents visited here a couple of months ago, Dad didn't have a mouse to use with his laptop so I _gave_ him mine.
Unfortunately, it means I've been unplugging and reconnecting my MX mouse whenever I need one. It's a time-suck.

In PT the cheapest supplier is: **€27.90** (including shipping)
https://www.kuantokusta.pt/informatica/Perifericos/Ratos-para-PC/Logitech-Mouse-M330-Silent-Plus-p-1-488389

@iteles any objection to me adding ***two*** of these to the "CC Box"?

**Comment by iteles** [comment]
None at all. As discussed, these have been ordered 👍

**Comment by nelsonic** [comment]
@iteles thanks for placing the order. 🙌

**Comment by nelsonic** [comment]
Been using these Silent Plus mice 🐁  for the past 9 months and it's been great. 
Gave one of them to my dad and he loves it too.
Closing. ✅
