### ISSUE TITLE
New Kindle

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/nelsonic.github.io#86]
I had a kindle back in the day ... But after reading _many_ books on it (_and before I could backup my clippings/highlights/notes_) it got _accidentally_ wiped. this made me :cry: because when I read a book I like to take notes and if those notes go missing (_usually when I lend a physical book to a "friend" who ends up not returning the book!!_) I get :disappointed: ...

Fast forward a few _years_ and I think I'm ready to take the _plunge_ again...

**Question**: Can you _export_ the clippings from a PDF book?
Apparently, yes: http://www.nathancolquhoun.com/2012/11/26/export-notes-and-highlights-from-pdf-on-your-kindle

relates to: #85

**Comment by nelsonic** [comment]
Kindle Refurbished Prices: http://www.amazon.co.uk/b?node=3645003031
<img width="1643" alt="kindle-refurbished-prices" src="https://cloud.githubusercontent.com/assets/194400/11319805/8ea4976a-907b-11e5-8e0d-38d1c697f899.png">

**Comment by nelsonic** [comment]
Brack Friday Bunduru Kindle PaperWhite 3G: http://www.amazon.co.uk/dp/B00CTW9EV8/ref=gbps_tit_m-3_3827_d462acef?pf_rd_p=762303827&pf_rd_s=merchandised-search-3&pf_rd_t=101&pf_rd_i=161428031&pf_rd_m=A3P5ROKL5A1OLE&pf_rd_r=0N4YDFQGM43VTAJ3D3KV
<img width="271" alt="paperwhite-3g" src="https://cloud.githubusercontent.com/assets/194400/11326172/245b91f8-915a-11e5-9e7d-5394ae78a986.png">

**Comment by iteles** [comment]
Every time I see the words 'Brack Friday Bunduru' in issues I smile _so big_ :smirk:

**Comment by nelsonic** [comment]
Ended up getting the latest version of the Paper White:

![paperwhite-deal](https://cloud.githubusercontent.com/assets/194400/11336971/5237eeaa-91e1-11e5-8a61-9b5bbe217929.png)

Paid the extra **£10** to _not_ have "_special offers_" ... don't know if that was the "right" decision...

**Comment by nelsonic** [comment]
Amazon _lowered_ the Kindle Paperwhite (_With Special Offers_) price to £79.99 so I cancelled the without-special offers order and got the £80 one. 
To remove the special offers (_without charge_): https://www.youtube.com/watch?v=t-03jlcGL1U
http://www.amazon.co.uk/gp/help/customer/display.html?nodeId=200671290
