### ISSUE TITLE
FAC monitors sponsorship proposal?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/nelsonic.github.io#9]
@iteles what do we think about drafting a proposal to sponsor the Pairing Monitors for FAC?
They would be useful for the Monday Night Meetups and weekend Workshops too...

**Comment by iteles** [comment]
Do we need to draft a proposal? Can't we just bring it up at the business meeting as a dwyl sponsorship?

**Comment by nelsonic** [comment]
We can present the case in a more effective way...

**Comment by nelsonic** [comment]
![image](https://cloud.githubusercontent.com/assets/194400/7649632/b850bbc8-fae6-11e4-994b-1312d98cc8e5.jpg)
http://pages.ebay.com/link/?nav=item.view&alt=web&id=171754683366

**Comment by nelsonic** [comment]
Outcome: We got a few monitors. The students _barely_ use them. "Graduates" do. 
anyway. closing.

**Comment by nelsonic** [comment]
This issue just came up in the "suggested" issues for an issue I am writing ... no idea why ... 🙄 

But I _never_ "regret" opening issues to capture my thoughts. 📝 
This thread feels like a _long_ time ago ... ⌛️ 
I still feel _really_ strongly about having big monitors for doing _any_ creative work. 💻 + 🖥 = 🌈 🚀 
I'm considering getting 4k 32's for Braga ... 😉 
Go big _and_ go @home https://github.com/dwyl/home 🏡
